.PHONY: install dev build start lint up down

install:
	npm install

dev:
	npm run dev

build:
	npm run build

start:
	npm run start

lint:
	npm run lint

up:
	cd .. && docker compose up --build web

down:
	cd .. && docker compose down
