-- innovations from the ROPS social innovation library (rops.krakow.pl), generated by
-- media/build_app_seed.py from media/innovations.json; do not edit by hand.
-- compose `seed-embed` embeds them; page_url holds the film. ON CONFLICT keeps admin edits
-- and the rows 007 already seeds (hop-hop, himalaje-autyzmu, gra-o-zdrowie).
INSERT INTO innovations (id, title, content, summary, tags, city, page_url, status)
VALUES
    (
        'agencja-pracy-incydentalnej',
        'Agencja pracy incydentalnej',
        'Problem: Innowacja odpowiada na trudność w powrocie na rynek pracy osób pozostajacych w głębokim/wielowymiarowym kryzysie

Rozwiązanie: W ramach modelu działania „Agencja Pracy Incydentalnej” (API) osoby doświadczające wielowarstwowych deficytów mają możliwość podjęcia pracy na zasadach nierejestrowanych działalności gospodarczych. Oferta wykonywanych zadań jest każdorazowo dopasowywana do ich preferencji, możliwości oraz uwarunkowań obecnej sytuacji życiowej. API w założeniu ma maksymalnie odformalizować pracę, tak, by stała się dostępna dla osób, które w danym momencie życia nie są w stanie podjąć zatrudnienia w ramach najczęściej wybieranych rozwiązań (umowa o pracę oraz umów cywilnoprawnych takich jak umowa zlecenie, umowa o dzieło). Model zakłada rezygnację z takich elementów zatrudnienia jak wymagana regularności pracy, sztywne dni i godziny jej wykonywania, prowadzenie skomplikowanej dokumentacji pracy itp.

Dla kogo: Osoby w kryzysie bezdomności i /lub psychicznym i/lub długotrwale bezrobotne i/lub z przeszłościa kryminalną i/lub osoby z niepełnosprawnością, który to kryzys skutkuje niemożnością podjęcia pracy wiążącej się z określonym czasem czy wymiarem

Kto może skorzystać: Agencje pracy, podmioty, organizacje pozarządowe zajmujące się aktywizacja zawodową osób w glębokim kryzysie

Czy to działa: Opracowany model wskazuje drogę legalnego zarabiania. Udział w innowacji umożliwił grupie docelowej podjęcie pracy, niewielka część grupy testującej zdecydowała się jednak z tej możliwości skorzystać (3 osoby). Wynika to z wielu barier, z których kluczowa wydaje się ta związana z brakiem gotowości do podjęcia takiej zmiany w swoim życiu, zwłaszcza, że wiązałaby się ona z częściową lub pełną rezygnacją z pobierania świadczeń socjalnych. W związku z krótkim okresem realizacji projektu, pojawiły się trudności istotnie wpływające na osiągnięcie efektów, jak chociażby niewielkie zaangażowanie zleceniodawców. W związku ze złożonością obszaru wsparcia, wydaje się to pewnym osiągnięciem i obiecującym początkiem dla dalszych zmian.

Autorzy: Fundacja Pestka

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'W ramach modelu działania „Agencja Pracy Incydentalnej” (API) osoby doświadczające wielowarstwowych deficytów mają możliwość podjęcia pracy na zasadach nierejestrowanych działalności gospodarczych. Oferta wykonywanych zadań jest każdorazowo dopasowywana do ich preferencji, możliwości oraz uwarunkowań obecnej sytuacji życiowej. API w założeniu ma maksymalnie odformalizować pracę, tak, by stała się dostępna dla osób, które w danym momencie życia nie są w stanie podjąć zatrudnienia w ramach najczęściej wybieranych rozwiązań (umowa o pracę oraz umów cywilnoprawnych takich jak umowa zlecenie, umowa o dzieło). Model zakłada rezygnację z takich elementów zatrudnienia jak wymagana regularności pracy, sztywne dni i godziny jej wykonywania, prowadzenie skomplikowanej dokumentacji pracy itp.',
        ARRAY['type:innovation', 'area:ubostwo', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'autyzm-i-ja',
        'AuTyzm i ja',
        'Problem: Innowacja jest odpowiedzią na trudności w nawiązywaniu kontaktów, kontynuowaniu lub podtrzymaniu interakcji z drugą osobą, brak kontaktu wzrokowego - szczególnie na wczesnym etapie rozwoju dziecka, brak możliwości rozwinięcia potencjału młodego człowieka oraz ograniczony dostęp do placówek edukacyjnych.

Rozwiązanie: Przygotowany w ramach innowacji przewodnik zawiera informacje o tym, jak wspierać dzieci w spektrum autyzmu. Znajdują się w nim m.in. wskazówki na temat wiedzy, w jaką należy wyposażyć osoby z ich otoczenia, by zwiększyć szansę na aklimatyzację i integrację w społeczeństwie. Przewodnik ma na celu wsparcie zarówno opiekunów, jak i nauczycieli, którzy dzięki dostępowi do aktualnych, nowoczesnych form pracy z dzieckiem, będą w stanie zapewnić naukę dzieciom w spektrum autyzmu. Przygotowany jednocześnie dzienniczek obserwacji online to narzędzie do obserwacji ważnych parametrów zachowań dzieci zarówno w domu, jak i w przedszkolu. Pozwala on szybciej wyłapać nowe zachowania lub zmianę w dotychczasowych wzorcach zachowań.

Dla kogo: Dzieci w wieku przedszkolnym ze spektrum autyzmu.

Kto może skorzystać: Placówki edukacji przedszkolnej, placówki wczesnej interwencji, szkoły.

Czy to działa: Rozwiązanie rzeczywiście wspiera we wspólnym i kierunkowym myśleniu o edukacji i rozwoju danego dziecka rodziców i nauczycieli / wychowawców w przedszkolu. Narzędzie on-line daje możliwość obserwacji zachowania dziecka i dostrzegania najmniejszych sygnałów zmian, dzięki którym można przeanalizować zmiany w diecie, czy zachowaniu np. innych domowników, które wpływają za zachowanie dziecka w przedszkolu czy na odwrót.

Autorzy: Uniwersytet Medyczny im. K. Marcinkowskiego w Poznaniu

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Przygotowany w ramach innowacji przewodnik zawiera informacje o tym, jak wspierać dzieci w spektrum autyzmu. Znajdują się w nim m.in. wskazówki na temat wiedzy, w jaką należy wyposażyć osoby z ich otoczenia, by zwiększyć szansę na aklimatyzację i integrację w społeczeństwie. Przewodnik ma na celu wsparcie zarówno opiekunów, jak i nauczycieli, którzy dzięki dostępowi do aktualnych, nowoczesnych form pracy z dzieckiem, będą w stanie zapewnić naukę dzieciom w spektrum autyzmu. Przygotowany jednocześnie dzienniczek obserwacji online to narzędzie do obserwacji ważnych parametrów zachowań dzieci zarówno w domu, jak i w przedszkolu. Pozwala on szybciej wyłapać nowe zachowania lub zmianę w dotychczasowych wzorcach zachowań.',
        ARRAY['type:innovation', 'area:niepelnosprawnosc', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'bajkala',
        'Bajkala',
        'Problem: Innowacja odpowiada na wyzwanie skutecznej integracja migrantów czeczeńskich (w szczególności dzieci), których prawidłowe funkcjonowanie w nowym kraju utrudniają bariery kulturowe, językowe, prawne i psychologiczne.

Rozwiązanie: Bajkala - to zestaw składający się z drewnianej lampki ledowej, z wbudowanym odtwarzaczem mp3 emitującym nagranie bajki, autorskie opracowanie bajki w języku polskim oraz rosyjskim/czeczeńskim, książeczki zawierającej tekst bajki w języku polskim oraz rosyjskim/czeczeńskim oraz słowniczek. Lampka, prócz dawania łagodnego światła, emituje nagrania bajek z polskiego kręgu kulturowego, które mają istotne podobieństwa do opowieści z kręgu kulturowego odbiorcy.

Dla kogo: Dzieci czeczeńskie przebywające w Polsce pod opieką rodziny, z nadanym statusem pobytu pozwalającymi na samodzielne funkcjonowanie rodziny

Kto może skorzystać: Ośrodki migracyjne, szkoły podstawowe do których uczęszczają migranci, organizacje pozarządowe wspierające aktywną integrację uchodźców.

Czy to działa: Podjęte działania wykazały skuteczność mechanizmu w uruchomieniu motywacji do słuchania polskich bajek oraz w poszerzaniu kompetencji językowych. Sama forma domku okazała się także skuteczna w budowaniu sprzyjającej rozwojowi atmosfery i poprzez pozytywne skojarzenia wspierała atmosferę bezpieczeństwa i komfortu. Jednocześnie, długofalowe efekty, aby zaistnieć, wymagałyby znacznego zwiększenia skali działania, a także poszerzenia treści dostępnych w ramach tego rozwiązania. Wydaje się jednak, na podstawie doświadczeń z grupą testującą, że innowacja ma potencjał do wspierania integracji dzieci czeczeńskich w kulturze polskiej, a także zwiększania poczucia ich komfortu w bardzo trudnej sytuacji jakiej znajdują się dzieci uchodźcze.

Autorzy: Maria Lorenc, Maciej Parol

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Bajkala - to zestaw składający się z drewnianej lampki ledowej, z wbudowanym odtwarzaczem mp3 emitującym nagranie bajki, autorskie opracowanie bajki w języku polskim oraz rosyjskim/czeczeńskim, książeczki zawierającej tekst bajki w języku polskim oraz rosyjskim/czeczeńskim oraz słowniczek. Lampka, prócz dawania łagodnego światła, emituje nagrania bajek z polskiego kręgu kulturowego, które mają istotne podobieństwa do opowieści z kręgu kulturowego odbiorcy.',
        ARRAY['type:innovation', 'area:integracja-cudzoziemcow', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'bawita',
        'BaWita',
        'Problem: Innowacja odpowiada na problem rozpowszechnianiasię zespołów otępiennych u osób w podeszłym wieku i pozwala zwiększyć ograniczony wachlarz narzędzi rehabilitacyjnych dedykowanych osobom dorosłym.

Rozwiązanie: Narzędzie rehabilitacyjne w postaci drewnianej tablicy wyposażonej w siedem ruchomych elementów służących do wielopłaszczyznowej stymulacji i usprawniania funkcji pamięciowych, manualnych i organizacji dnia dla osób ze schorzeniami dementywnymi.

Dla kogo: Dorosłe osoby cierpiące na zespół otępienny we wczesnym stadium oraz osoby rehabilitowane pamięciowo po udarach i wylewach.

Kto może skorzystać: Placówki wsparcia dziennego seniorów, domy pomocy społecznej, miejskie dzienne domy pomocy społecznej, warsztaty terapii zajęciowej, osoby indywidualne.

Czy to działa: Test innowacji potwierdził jej skuteczność w procesie poprawy pamięci proceduralnej. Wykazał także szereg dodatkowych istotnych dla rehabilitacji osób starszych efektów – poprawa motoryki małej, rozwijanie wyobraźni, skojarzeń, poprawa fluencji i rozbudowywanie pomięci słownej, a nawet poprawa funkcjonowania społecznego i integracji.

Autorzy: Maria Lorenc, Maciej Parol

Program: INKUBATOR WŁĄCZENIA SPOŁECZNEGO

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Narzędzie rehabilitacyjne w postaci drewnianej tablicy wyposażonej w siedem ruchomych elementów służących do wielopłaszczyznowej stymulacji i usprawniania funkcji pamięciowych, manualnych i organizacji dnia dla osób ze schorzeniami dementywnymi.',
        ARRAY['type:innovation', 'area:seniorzy', 'source:rops-biblioteka']::text[],
        '',
        'https://www.youtube.com/watch?v=o7UhDlebLJo',
        'published'
    ),
    (
        'bez-presji-z-depresji',
        'Bez presji z depresji',
        'Problem: Innowacja odpowiada na potrzeby dzieci i młodzieży borykających się z problemami zdrowia psychicznego, które powracają do środowiska szkolnego po dłuższej nieobecności.

Rozwiązanie: Komplet materiałów psychoedukacyjnych w postaci kart pracy i ćwiczeń dla dzieci i młodzieży zmagających się z trudnościami w powrocie do funkcjonowania w życiu społecznym i szkolnym po nieobecności związanej z długoterminową terapią lub leczeniem psychiatrycznym. Innowacja obejmuje zasięgiem także rodzinę i środowisko szkolne dziecka, tworząc sieć wsparcia najbliższego otoczenia. Wypracowane materiały psychoedukacyjne stanowią pomoc wspierającą dziecko i jego najbliższe otoczenie (rodzina, nauczyciele, klasa) w powrocie do równowagi psychicznej i emocjonalnej, a jednocześnie uświadamiają nauczycielom i rówieśnikom skalę problemu oraz zwiększają zaangażowanie w pomoc osobom w kryzysie psychicznym.

Dla kogo: Dzieci i młodzież w wieku od 10 do 13 lat (od 4 do 8 klasy szkoły podstawowej), które wracają do czynnego funkcjonowania w życiu społecznym po dłuższej nieobecności spowodowanej trudnościami w sferze emocji, terapią lub leczeniem psychiatrycznym związanym z zaburzeniami nastroju, kryzysami psychicznymi, stanami lękowymi oraz rodzice, rówieśnicy oraz nauczyciele, osób zmagających się z trudnościami w powrocie do funkcjonowania w życiu społecznym i szkolnym.

Kto może skorzystać: Placówki oświatowe, poradnie psychologiczno-pedagogiczne, ośrodki interwencji kryzysowej, szpitale psychiatryczne z oddziałami dla dzieci i młodzieży.

Czy to działa: Wyniki testu pokazały, że dzięki skorzystaniu z innowacji m.in. wzrosło samopoczucie uczniów (w obszarze funkcjonowania społecznego) oraz wzrosła samoocena nauczycieli i rodziców (w obszarze znajomości narzędzi i sposobów wspierania). Minusem rozwiązania jest fakt, że podobne materiały można znaleźć w innych źródłach, a warunkiem powodzenia projektu staje się w tej sytuacji spójne, kompleksowe działanie z wielu stron (co jest wyzwaniem) i wykorzystanie kompletu produktów.

Autorzy: Instytut HR Ewa Gordziej-Niewczyk

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Komplet materiałów psychoedukacyjnych w postaci kart pracy i ćwiczeń dla dzieci i młodzieży zmagających się z trudnościami w powrocie do funkcjonowania w życiu społecznym i szkolnym po nieobecności związanej z długoterminową terapią lub leczeniem psychiatrycznym. Innowacja obejmuje zasięgiem także rodzinę i środowisko szkolne dziecka, tworząc sieć wsparcia najbliższego otoczenia. Wypracowane materiały psychoedukacyjne stanowią pomoc wspierającą dziecko i jego najbliższe otoczenie (rodzina, nauczyciele, klasa) w powrocie do równowagi psychicznej i emocjonalnej, a jednocześnie uświadamiają nauczycielom i rówieśnikom skalę problemu oraz zwiększają zaangażowanie w pomoc osobom w kryzysie psychicznym.',
        ARRAY['type:innovation', 'area:rodzina-i-piecza-zastepcza', 'source:rops-biblioteka']::text[],
        '',
        'https://www.youtube.com/watch?v=Bt6FF2Z5XU4',
        'published'
    ),
    (
        'bez-stresu-do-sukcesu-terapia-neurologiczna-przyjazna-dziecku',
        'Bez stresu do sukcesu - terapia neurologiczna przyjazna dziecku',
        'Problem: Innowacja odpowiada na brak dostępu do skutecznych terapii kompleksowych dla dzieci poniżej 3. roku życia, które - oddziałując na psychikę - umożliwią zwiększenie skuteczności leczenia właściwego.

Rozwiązanie: Innowacja skupia się na połączeniu metod leczenia i terapeutyzowania dzieci i niemowląt z zaburzeniami funkcji układu nerwowego (fizjoterapia, dogoterapii psycholog dziecięcy), dążąc do uzyskania efektu synergii wprowadzonych metod. W ramach innowacji powstał model fizjoterapii neurologicznej dzieci z niepełnosprawnościami, który zakłada integrację i synergię oddziaływań metody NDT Bobath oraz dodatkowych stymulantów psychofizycznych (dogoterapii i psychologa dziecięcego). Wprowadzenie do terapii dodatkowych bodźców w początkowym etapie zajęć ma skutkować regulacją poziomu napięć i umożliwić właściwą terapię leczniczą w sposób szybszy i efektywniejszy.

Dla kogo: Dzieci z niepełnosprawnością i zagrożone trwałą niepełnosprawnością między 6. miesiącem a 3. rokiem życia, dzieci obarczone trudnościami rozwojowymi, które odmawiają współpracy z prowadzącym, ponieważ ćwiczenia rehabilitacyjne wykraczają poza ich możliwości koncentracji i stanowią dla nich dyskomfort.

Kto może skorzystać: Placówki fizjoterapeutyczne, rodzice/opiekunowie, ośrodki wczesnego wspomagania rozwoju, dzienne i całodobowe oddziały rehabilitacyjne.

Czy to działa: Analizując wyniki testów można przyjąć, że współpraca dwóch terapeutów przynosi oczekiwane efekty (dziewięcioro na dziesięć dzieci/opiekunów potwierdziło ich skuteczność). Pozytywny wpływ udziału drugiej osoby w procesie terapeutycznym najbardziej zauważalny był podczas pracy manualnej z dzieckiem. Większość z dzieci nie reagowała na dotyk dzięki temu fizjoterapeuta mógł pracować znacznie dłużej i efektywniej. Terapeuta mógł także skupić się dłużej na pracy z ciałem dziecka jednocześnie nie poświęcając czasu na wyciszanie trudnych emocji zakłócających przebieg terapii.

Autorzy: Marta Grela

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Innowacja skupia się na połączeniu metod leczenia i terapeutyzowania dzieci i niemowląt z zaburzeniami funkcji układu nerwowego (fizjoterapia, dogoterapii psycholog dziecięcy), dążąc do uzyskania efektu synergii wprowadzonych metod. W ramach innowacji powstał model fizjoterapii neurologicznej dzieci z niepełnosprawnościami, który zakłada integrację i synergię oddziaływań metody NDT Bobath oraz dodatkowych stymulantów psychofizycznych (dogoterapii i psychologa dziecięcego). Wprowadzenie do terapii dodatkowych bodźców w początkowym etapie zajęć ma skutkować regulacją poziomu napięć i umożliwić właściwą terapię leczniczą w sposób szybszy i efektywniejszy.',
        ARRAY['type:innovation', 'area:rodzina-i-piecza-zastepcza', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'biustspinka',
        'BiustSPINKA',
        'Problem: Rozwiązanie stanowi odpowiedź na problem braku odpowiednich artykułów i urządzeń wspierających samodzielne ubieranie się kobiet z dysfunkcją ręki.

Rozwiązanie: Ptoste, tanie i praktyczne urządzenie wykorzystujące taśmę slap, wspomagające zakładanie biustonosza o nazwie BiustSPINKA. Urządzenie jest skierowane do kobiet posiadających różnego typu ograniczenia ruchowe i fizyczne ze względu na swoją niepełnosprawność, schorzenia, wypadek, chorobę lub funkcjonalność jednego ramienia. Ma wspomagać i zwiększać wygodę w procesie zakładania, zapinania i zdejmowania biustonosza.

Dla kogo: Kobiety posiadające różnego rodzaju ograniczenia fizyczne i ruchowe, które utrudniają lub uniemożliwiają samodzielne założenie biustonosza (m.in. poruszające się na wózku, z niepełnosprawnością wrodzoną, z mózgowym porażeniem dziecięcym, z niepełnosprawnością nabytą w wyniku wypadku lub choroby, kobiety z dysfunkcją ramienia, kobiety po amputacji piersi, kobiety z zaburzeniami ruchu w wyniku udaru lub przebytej operacji, kobiety cierpiące na otyłość).

Kto może skorzystać: Gabinety rehabilitacyjne, szkoły, szpitale, sklepy z bielizną, przychodnie, oddziały rehabilitacyjne.

Czy to działa: Użyteczność produktu zasadza się w jego prostocie oraz możliwości całkowitej samodzielności osoby z niepełnosprawnością. Natomiast testowanie wykazało, że mimo wszystko produkt nie jest dla wszystkich wygodny w użyciu. Użyteczność produktu zostanie niewątpliwie docenione przez sprawniejsze osoby, które czynność zapinania biustonosza wykonają jedną, sprawną ręką. Wątpliwość w obszarze użyteczności dotyczy specyficznego ruchu, który wiąże się z użyciem produktu. Taśma slap, która oplata użytkowniczkę w miejscu pod biustem, musi być dosyć mocno uderzona w celu oplecenia jej wokół ciała. Dodatkowo wymaga także precyzyjnych ruchów, w celu zapięcia biustonosza na urządzenie. To wszystko sprawia, że produkt nie będzie jednakowo użyteczny dla całej, pierwotnie zakładanej grupy docelowej.

Autorzy: Karpatia Sp. z o. o

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Ptoste, tanie i praktyczne urządzenie wykorzystujące taśmę slap, wspomagające zakładanie biustonosza o nazwie BiustSPINKA. Urządzenie jest skierowane do kobiet posiadających różnego typu ograniczenia ruchowe i fizyczne ze względu na swoją niepełnosprawność, schorzenia, wypadek, chorobę lub funkcjonalność jednego ramienia. Ma wspomagać i zwiększać wygodę w procesie zakładania, zapinania i zdejmowania biustonosza.',
        ARRAY['type:innovation', 'area:niepelnosprawnosc', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'blue-sea-eye',
        'Blue Sea Eye',
        'Problem: Innowacja odpowiada na brak sprzętu umożliwiającego nawigowanie żeglarzy z dysfunkcją narządu wzroku i utrudniony dostęp osób z dysfunkcją narządu wzroku do żeglarstwa.

Rozwiązanie: Urządzenie mobilne (przenośny wskaźnik kursu kompasowego i wychylenia steru) połączone z aplikacją, która umożliwia osobom niewidomym i niedowidzącym samodzielne sterowanie jednostką pływającą. Urządzenie jest niezależne od aparatury pokładowej a jego funkcją jest precyzyjne generowanie informacji (aktualny kurs, odejście od kursu zadanego, aktualne położenie steru) a następnie przekazywanie ich do aplikacji uruchamianej na smartfonie użytkownika wyposażonym w oprogramowanie odczytu ekranu mową syntetyczną. Równolegle uczestnik jest powiadamiany o zmianach kursu za pomocą serii krótkich dźwięków o różnej częstotliwości, co pozwala na uzyskanie informacji szybciej niż za pomocą syntezy mowy, skracając tym samym czas reakcji na zachodzące zmiany kursu.

Dla kogo: Osoby niewidome, osoby niedowidzące.

Kto może skorzystać: Osoby z dysfunkcją narządu wzroku, podmioty organizujące rejsy uwzględniające załogantów z z dysfunkcją narządu wzroku, kluby żeglarskie, organizacje pozarządowe wspierające osoby z dysfunkcją narządu wzroku.

Czy to działa: Rozwiązanie zostało bardzo dobrze ocenione zarówno przez realizatorów innowacji, jak i członków grupy testującej, którzy wprost twierdzili „nie czuję się już jak ‘worek ziemniaków’ który ktoś musi przesuwać na pokładzie”. Blue Sea Eye jest urządzeniem dobrze zaprojektowanym, pozwalającym niewidomym, w sprzyjających warunkach pogodowych, samodzielnie sterować jednostką pływającą. Aby przedłużyć trwałość urządzenia i poprawić jego wydajność należy jednak podjąć dalsze działania, m.in. przenieść układy zawarte w gotowych komponentach do jednego układu scalonego i opracować filtrowanie i rozdzielanie zasilania.

Autorzy: Fundacja Zobaczyć Morze

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Urządzenie mobilne (przenośny wskaźnik kursu kompasowego i wychylenia steru) połączone z aplikacją, która umożliwia osobom niewidomym i niedowidzącym samodzielne sterowanie jednostką pływającą. Urządzenie jest niezależne od aparatury pokładowej a jego funkcją jest precyzyjne generowanie informacji (aktualny kurs, odejście od kursu zadanego, aktualne położenie steru) a następnie przekazywanie ich do aplikacji uruchamianej na smartfonie użytkownika wyposażonym w oprogramowanie odczytu ekranu mową syntetyczną. Równolegle uczestnik jest powiadamiany o zmianach kursu za pomocą serii krótkich dźwięków o różnej częstotliwości, co pozwala na uzyskanie informacji szybciej niż za pomocą syntezy mowy, skracając tym samym czas reakcji na zachodzące zmiany kursu.',
        ARRAY['type:innovation', 'area:niepelnosprawnosc', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'brzuszkole-brzuszek-zostaje-w-przedszkolu',
        'Brzuszkole - brzuszek zostaje w przedszkolu',
        'Problem: Innowacja dotyczy takich problemów jak przeciwdziałanie problemowi otyłości nadwagi i otyłości u dzieci w wieku 4-7 lat.

Rozwiązanie: Materiał edukacyjny zawierający zalecenia dotyczące diety i zdrowego stylu życia dzieci w wieku 4 – 7 lat dostępny w gabinetach lekarskich i wykorzystywany w szczególności podczas wizyt profilaktycznych cztero- i sześcio- lub siedmiolatków (tzw. bilanse zdrowia). Tekst zaleceń jest kierowany do opiekunów, jednak ilustracje przyciągają uwagę dzieci i zachęcają do podejmowania tematu zdrowego stylu życia.

Dla kogo: Dzieci w wieku 4-7 la tz nadwagą/otyłością lub ryzykiem nadwagi/otyłości

Kto może skorzystać: Placówki medyczne, przedszkola, organizacje pozarządowe.

Czy to działa: Rozwiązanie – poprzez zwiększenie dostępności do rzetelnych materiałów – jest skuteczne w podniesieniu wiedzy u rodziców o zasadach zdrowego odżywiania dzieci w wieku przedszkolny. Ponadto jest atrakcyjnym materiałem także dla samych dzieci, co sprawia, że jest skuteczne także w wymiarze zwiększania zainteresowania tym tematem dzieci. Testy wskazały, że kluczowe znaczenie w zainicjowaniu pożadanych zmian, ale także w utrzymywaniu ich trwałości ma wsparcie pediatry w tym procesie.

Autorzy: Justyna Laskowska

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Materiał edukacyjny zawierający zalecenia dotyczące diety i zdrowego stylu życia dzieci w wieku 4 – 7 lat dostępny w gabinetach lekarskich i wykorzystywany w szczególności podczas wizyt profilaktycznych cztero- i sześcio- lub siedmiolatków (tzw. bilanse zdrowia). Tekst zaleceń jest kierowany do opiekunów, jednak ilustracje przyciągają uwagę dzieci i zachęcają do podejmowania tematu zdrowego stylu życia.',
        ARRAY['type:innovation', 'area:rodzina-i-piecza-zastepcza', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'centrum-antydepresyjne',
        'Centrum antydepresyjne',
        'Problem: Innowacja jest odpowiedzią na niski dostęp do metod pracy z samotnymi osobami starszymi, u których występuje ryzyko depresji, prób samobójczych itp., które mieszkają na terenach wiejskich.

Rozwiązanie: Rozwiązanie stanowi nowatorską metodę pracy z seniorem w stanach depresyjnych z zastosowaniem dogo- i felinoterapii, które mają na celu zmniejszenie ryzyka wystąpienia epizodów depresyjnych i zachowań suicydalnych. Opiera się na świadczeniu wsparcia w środowisku domowym osoby starszej oraz osób z jej najbliższego otoczenia.

Dla kogo: Osoby starsze wymagające opieki w miejscu zamieszkania i ich opiekunowie

Kto może skorzystać: Podmioty organizujące usługi opiekuńcze w miejscu zamieszkania, w tym jednostki samorządu terytorialnego, organizacje pozarządowe, podmioty ekonomii społecznej.

Autorzy: Gmina Miechów

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Rozwiązanie stanowi nowatorską metodę pracy z seniorem w stanach depresyjnych z zastosowaniem dogo- i felinoterapii, które mają na celu zmniejszenie ryzyka wystąpienia epizodów depresyjnych i zachowań suicydalnych. Opiera się na świadczeniu wsparcia w środowisku domowym osoby starszej oraz osób z jej najbliższego otoczenia.',
        ARRAY['type:innovation', 'area:seniorzy', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'chlap-pro',
        'Chlap Pro',
        'Problem: Innowacja odpowiada na brak odpowiedniego zabezpieczenia protez kończyn dolnych przed zamoknięciem, co może skutkować szybszym zużyciem elementów protez i jej zniszczeniem

Rozwiązanie: Innowację stanowi chlapoodporny ochraniacz protezy nogi ChlapPro. Produkt zapewnia ochronę przed zachlapaniem tych elementów w protezie, które nie są odporne na wodę. W ramach projektu powstały dwa rodzaje ochraniaczy dostosowanych do najpopularniejszych rodzajów protezy podudzia i uda.

Dla kogo: Osoby z protezami ud i podudzia

Kto może skorzystać: Osoby poruszające się z pomocą protez uda lub podudzia, ośrodki wsparcia osób z niepełnosprawnościami, urzędy miasta i gmin, na terenie których mieszkają osoby korzystające z protez.

Czy to działa: W ramach innowacji powstały ochraniacze na protezy. Testowanie wykazało przydatność takiego narzędzia oraz jego skuteczność w zapewnianiu ochrony przed zamoczeniem protez w ramach użytkowania w niekorzystnych warunkach pogodowych.

Autorzy: Klaudia Kaniewska

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Innowację stanowi chlapoodporny ochraniacz protezy nogi ChlapPro. Produkt zapewnia ochronę przed zachlapaniem tych elementów w protezie, które nie są odporne na wodę. W ramach projektu powstały dwa rodzaje ochraniaczy dostosowanych do najpopularniejszych rodzajów protezy podudzia i uda.',
        ARRAY['type:innovation', 'area:niepelnosprawnosc', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'cloudleg',
        'Cloudleg',
        'Problem: Innowacja odpowiada na dyskomfort wynikający z braku nóg u osób po amputacji lub z wrodzoną wadą braku kończyn powyżej kolan, które nie mogą lub nie chcą korzystać z protez funkcjonalnych/ortopedycznych.

Rozwiązanie: Metoda tworzenia i wykonania realistycznie wyglądających sztucznych nóg w formie protezy kosmetycznej dla osób poruszających się̨ na wózku. Rozwiązanie powstało z myślą o osobach po amputacji obu nóg powyżej kolan lub ich braku od urodzenia. Proteza Cloudleg pełni funkcję estetyczną, wizerunkową - nie jest produktem medycznym. W swojej wyjściowej formie jest gotowa do przycięcia na odpowiednią długość względem indywidualnych potrzeb użytkownika/użytkowniczki. Proteza jest utrzymana przy ciele za pomocą elementu trzymającego w postaci elastycznych szortów.

Dla kogo: Odbiorcy innowacji to osoby po amputacji kończyn dolnych powyżej kolan lub ich braku od urodzenia, niekorzystające z medycznych protez lub protez funkcjonalnych, na co dzień poruszające się na wózku, osoby które niedawno doświadczyły utraty nóg i dopiero oswajają się z nowym wizerunkiem.

Kto może skorzystać: Osoby indywidualne po amputacji kończyn dolnych, placówki rehabilitacyjne, szpitale, organizacje wspierające aktywizację osób z niepełnosprawnością ruchową, po amputacjach i poruszających się na wózku.

Czy to działa: Użyteczność innowacji należy ocenić wysoko. Zaobserwowane zmiany wpisały się w potrzeby grupy docelowej. Proponowany pomysł ma w założeniu spełniać funkcję estetyczną - kosmetyczną i przy zachowaniu odpowiedniej ceny produktu, może mieć wysoki stopień użyteczności. Ryzyko może się wiązać się z dostępem do protez – zakup protezy online może wywołać pewną nieufność wśród potencjalnych nabywców przyzwyczajonych do możliwości dokładnego przymierzenia protezy. Ryzyko to musi być niwelowanie poprzez działania informacyjno-promocyjne pokazujące inne (estetyczne, a nie medyczne) właściwości proponowanego produktu.

Autorzy: Bartłomiej Stroiński

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Metoda tworzenia i wykonania realistycznie wyglądających sztucznych nóg w formie protezy kosmetycznej dla osób poruszających się̨ na wózku. Rozwiązanie powstało z myślą o osobach po amputacji obu nóg powyżej kolan lub ich braku od urodzenia. Proteza Cloudleg pełni funkcję estetyczną, wizerunkową - nie jest produktem medycznym. W swojej wyjściowej formie jest gotowa do przycięcia na odpowiednią długość względem indywidualnych potrzeb użytkownika/użytkowniczki. Proteza jest utrzymana przy ciele za pomocą elementu trzymającego w postaci elastycznych szortów.',
        ARRAY['type:innovation', 'area:niepelnosprawnosc', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'cold-box',
        'Cold Box',
        'Problem: Innowacja odpowiada na trudności w zapewnianiu odpowiednich warunków przechowywania leków wymagających ciągłego chłodzenia i utrudnienia w podróżowaniu osób przyjmujących tego typu leki.

Rozwiązanie: Innowację stanowi niewielki, mobilny, wodoodszczelny pojemnik chłodzący służący do przechowywania osobistych leków (np. insuliny) w odpowiednich warunkach termicznych. Wyposażony jest w baterię, która umożliwia utrzymanie stałej, niskiej (4-7 stopni Celsjusza) temperatury bez konieczności trwałego korzystania ze stacjonarnych źródeł energii.

Dla kogo: Osoby chorujące na cukrzycę oraz inne osoby, które muszą mieć przy sobie leki wymagające stałego chłodzenia.

Kto może skorzystać: Osoby prywatne, apteki, przychodnie medyczne.

Czy to działa: Rozwiązanie zostało dobrze ocenione przez członków grupy testującej. Z satysfakcją korzystali oni z urządzenia w trakcie okresu testowania, byli zaciekawieni przedstawioną propozycją i kreowali różne pomysły na jego wykorzystanie w trakcie codziennych czynności, np. wycieczki plenerowej. Test wykazał jednak, że gabaryty urządzenia nadal nie są wystarczająco małe, by móc nosić je bez problemu w torebce czy plecaku.

Autorzy: Fundacja Mars

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Innowację stanowi niewielki, mobilny, wodoodszczelny pojemnik chłodzący służący do przechowywania osobistych leków (np. insuliny) w odpowiednich warunkach termicznych. Wyposażony jest w baterię, która umożliwia utrzymanie stałej, niskiej (4-7 stopni Celsjusza) temperatury bez konieczności trwałego korzystania ze stacjonarnych źródeł energii.',
        ARRAY['type:innovation', 'area:zdrowie', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'czas-na-aktywnosc',
        'Czas na aktywność!',
        'Problem: Innowacja odpowiada na problem bierności społecznej znacznej ilości osób z niepełnosprawnością inetelektualnie po ukończeniu edukacji szkolnej. Samodzielnie rzadko podejmują działania, z trudem korzystają z oferty miasta, choć jest ona dla nich interesująca, bazując głównie na propozycjach kierowanych do nich przez placówki, pod opieką których pozostają (ŚDS, WTZ).

Rozwiązanie: "Czas na aktywność!" to internetowa platforma dla dorosłych osób z zespołem Downa, która umożliwia im prowadzenie aktywnego i samodzielnego życia kulturalno-społecznego (z asystą wolontariuszy) w swojej miejscowości na miarę swoich potrzeb i możliwości. Poprzez uproszczony interfejs, zbudowany z elementów graficznych i dźwiękowych - ma w czytelny i przejrzysty sposób przekazywać informacje osobom z niepełnosprawnością intelektualną.

Dla kogo: Osoby z niepełnosprawnością intelektualną w wieku 18-25 lat. Innowacja szczególnie kierowana jest do dorosłych osób z zespołem Downa

Kto może skorzystać: Instytucje wspierające i świadczące usługi na rzecz osób niepełnoprawnych intelektualnie, w tym osób z zespołem Downa, np.: Środowiskowe Domy Samopomocy, Warsztaty Terapii Zajęciowej, szkoły,organizacje pozarządowe.

Czy to działa: Rozwiązanie trafnie odpowiada na potrzeby grupy docelowej i pozwala samodzielnie organizaować swój czas wolny i budować więzi społeczne.

Autorzy: Stowarzyszenie Rodziców i Przyjaciół Dzieci z Zespołem Downa TĘCZA w Krakowie, Agata Krzyżek, Joanna Kociołek, Grażyna Banach-Kociołek, Agnieszka Jankiewicz

Program: MAŁOPOLSKI INKUBATOR INNOWACJI SPOŁECZNYCH

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        '"Czas na aktywność!" to internetowa platforma dla dorosłych osób z zespołem Downa, która umożliwia im prowadzenie aktywnego i samodzielnego życia kulturalno-społecznego (z asystą wolontariuszy) w swojej miejscowości na miarę swoich potrzeb i możliwości. Poprzez uproszczony interfejs, zbudowany z elementów graficznych i dźwiękowych - ma w czytelny i przejrzysty sposób przekazywać informacje osobom z niepełnosprawnością intelektualną.',
        ARRAY['type:innovation', 'area:rodzina-i-piecza-zastepcza', 'source:rops-biblioteka']::text[],
        '',
        'https://www.youtube.com/watch?v=QgkpdYndqNU',
        'published'
    ),
    (
        'czytamoda',
        'Czytamoda',
        'Problem: Innowacja jest odpowiedzią na trudności w wyborze ubrań osób z niepełnosprawnością wzroku i konieczność posiadania asysty w trakcie zakupów.

Rozwiązanie: W ramach innowacji powstała aplikacja uzupełniająca tradycyjne opisy ubrań w sklepach online oraz stacjonarnych o audiodeskrypcję. Dzięki temu rozwiązaniu osoby z niepełnosprawnością wzroku mogą wysłuchać opisów produktów, informacji na temat ich stylu i wykonania, a później na tej podstawie podjąć decyzję o zakupie konkretnego elementu garderoby.

Dla kogo: Osoby niewidome i osoby z zaburzeniami widzenia

Kto może skorzystać: Sklepy odzieżone stacjonarne oraz online, centra handlowe.

Czy to działa: Rozwiązanie zaproponowane w ramach innowacji przyczyniło się do wzrostu jakości życia osób z niepełnosprawnością wzroku, które dzięki niemu są w stanie robić zakupy odzieżowe bez asysty. Znalazło to swoje odzwierciedlenie w ich lepszym samopoczuciu, które wynika z noszenia ubrań lepiej dopasowanych do ich stylu i upodobań. Jednakże ze względu na trudności w zakresie wdrożenia go na większą skalę, rozwiązanie to na ten moment rekomendowane jest dla sklepów/butików z mniejszym asortymentem.

Autorzy: Fundacja Arete Centrum Edukacji Twórczej

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'W ramach innowacji powstała aplikacja uzupełniająca tradycyjne opisy ubrań w sklepach online oraz stacjonarnych o audiodeskrypcję. Dzięki temu rozwiązaniu osoby z niepełnosprawnością wzroku mogą wysłuchać opisów produktów, informacji na temat ich stylu i wykonania, a później na tej podstawie podjąć decyzję o zakupie konkretnego elementu garderoby.',
        ARRAY['type:innovation', 'area:niepelnosprawnosc', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'dialog-ponad-kulturami',
        'Dialog ponad kulturami',
        'Problem: Innowacja odpowiada na problem uprowadzeń rodzicielskich i konfliktów pomiędzy rodzicami pochodzącymi z różnych krajów/kultur

Rozwiązanie: Wystandaryzowany Modelu Mediacji Transgranicznych mający zastosowanie w przypadku porwań lub zagrożenia porwaniem rodzicielskim dla par/rodziców dzieci pochodzących z odmiennych kręgów kulturowych będących w konflikcie dotyczącym głównie ustalenia miejsca pobytu dziecka oraz sprawowania władzy rodzicielskiej. Model zakłada syntezę rozwiązań prawnych, psychologicznych, międzykulturowych i technik negocjacyjnych w procesie mediacji transgranicznych. Model ma charakter uniwersalny i może być zastosowany przed wniesieniem sprawy do sądu, w trakcie postępowania sądowego, a także po jego zakończeniu.

Dla kogo: Dzieci doświadczające porwania rodzicielskiego, dzieci zagrożone porwaniem rodzicielskim, dzieci obywateli różnych krajów, których rodzice pozostają w konflikcie rodzicielskim

Kto może skorzystać: Mediatorzy, prawnicy, pracownicy służb, którzy stykają się z problemem porwań rodzicielskich w swojej pracy, szkoły i uczelnie, w których uczą się dzieci pochodzące z odmiennych kręgów kulturowych, ośrodki pomocy rodzinie, centra praw kobiet.

Czy to działa: Innowacja realnie odpowiada na potrzeby rodzin międzykulturowych dotkniętych konfliktem i cechuje się wysoką skutecznością.Dodatkowo rozwiązanie dobrze wpisuje się w potrzeby pośrednich grup docelowych: mediatorów oraz innych interesariuszy pozostających w kontakcie formalnym i nieformalnym z osobami bezpośrednio zaangażowanymi w konflikt. Należy zauważyć fakt, ze testerzy w kilku przypadkach zdecydowali się kontynuować proces mediacji poza projektem, jak również podjęli dodatkowe działania np. rozpoczęcie własnej lub dzieci terapii psychologicznej.

Autorzy: Małgorzata Chachaj

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Wystandaryzowany Modelu Mediacji Transgranicznych mający zastosowanie w przypadku porwań lub zagrożenia porwaniem rodzicielskim dla par/rodziców dzieci pochodzących z odmiennych kręgów kulturowych będących w konflikcie dotyczącym głównie ustalenia miejsca pobytu dziecka oraz sprawowania władzy rodzicielskiej. Model zakłada syntezę rozwiązań prawnych, psychologicznych, międzykulturowych i technik negocjacyjnych w procesie mediacji transgranicznych. Model ma charakter uniwersalny i może być zastosowany przed wniesieniem sprawy do sądu, w trakcie postępowania sądowego, a także po jego zakończeniu.',
        ARRAY['type:innovation', 'area:integracja-cudzoziemcow', 'source:rops-biblioteka']::text[],
        '',
        'https://www.youtube.com/playlist?list=PLyL3RjFzJ8dH3ehTgdzxLYMF5YhNdnHEj',
        'published'
    ),
    (
        'dialog-ponad-kulturami-1',
        'Dialog ponad kulturami',
        'Problem: Innowacja odpowiada na trudność komunikowania się z uchodźcami afgańskimi, którzy przybyli do Polski w wyniku ewakuacji z Afganistanu w 2021 roku.

Rozwiązanie: Aplikacja mobilna stanowiąca rodzaj intuicyjnego komunikatora między uchodźcami z Afganistanu przebywającymi w Polsce w wyniku ewakuacji przez Wojsko Polskie oraz inne instytucje Państwa Polskiego, a społeczeństwem polskim. Aplikacja/komunikator została przygotowana w dwóch wersjach językowych: w języku darii i w języku polskim oraz w postaci piktogramów pomocnych do niektórych słów, dla niepiśmiennej części społeczności afgańskiej. Aplikacja zawiera praktyczne słownictwo z kilku obszarów tematycznych, m.in.: zdrowie, edukacja, praca, sprawy urzędowe.

Dla kogo: Mniejszość afgańskia przebywająca w Polsce

Kto może skorzystać: Mniejszość afgańska przebywająca w Polsce, pracownicy polskich instytucji publicznych takich jak: opieka medyczna, ośrodki pomocy społecznej, służby konsularne, urzędy działające na rzecz cudzoziemców w Polsce, instytucje kultury, instytucje edukacji, organizacje pozarządowe prowadzące działania na rzecz integracji społecznej cudzoziemców w Polsce, centra międzykulturowe.

Czy to działa: Częściowo zrealizowano zakładane cele – przygotowane i przetestowane narzędzie umożliwia prowadzenie bardzo podstawowej komunikacji osobom piśmiennym, niepiśmiennym raczej nie i nie wynika to wyłącznie z trudności w zastosowaniu adekwatnych piktogramów, ale z przyczyn niezależnych od innowatora – braku poczucia gotowości korzystania z tego typu narzędzia. Innowacja w wypracowanej formie zaspokaja w znacznym zakresie potrzebę osób piśmiennych, wymaga jednak naniesienia kluczowych zmian by umożliwić prowadzenie podstawowej komunikacji wśród osób niepiśmiennych.

Autorzy: Fundacja Human Doc

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Aplikacja mobilna stanowiąca rodzaj intuicyjnego komunikatora między uchodźcami z Afganistanu przebywającymi w Polsce w wyniku ewakuacji przez Wojsko Polskie oraz inne instytucje Państwa Polskiego, a społeczeństwem polskim. Aplikacja/komunikator została przygotowana w dwóch wersjach językowych: w języku darii i w języku polskim oraz w postaci piktogramów pomocnych do niektórych słów, dla niepiśmiennej części społeczności afgańskiej. Aplikacja zawiera praktyczne słownictwo z kilku obszarów tematycznych, m.in.: zdrowie, edukacja, praca, sprawy urzędowe.',
        ARRAY['type:innovation', 'area:integracja-cudzoziemcow', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'dostepna-polska',
        'Dostępna Polska',
        'Problem: Innowacja odpowiada na ograniczony dostęp do samodzielnej turystyki osób z niepełnosprawnością intelektualną i trudności w przyswojeniu informacji zawartych w zwykłych przewodnikach turystycznych przez osoby z niepełnosprawnością intelektualną w stopniu lekkim i umiarkowanym.

Rozwiązanie: Rozwiązanie stanowi komplet przewodników turystycznych, które zostały przystosowane do potrzeb osób z niepełnosprawnością intelektualną w stopniu lekkim i umiarkowanym. Zawarte w nich informacje będą w formie „easy to read”, opisując kompleksowo po dwa warianty tras turystycznych w trzech polskich miastach.

Dla kogo: Dorosłe osoby z niepełnosprawnością intelektualną w stopniu lekkim i umiarkowanym oraz ich rodziny.

Kto może skorzystać: Jednostki organizacyjne pomocy społecznej, organizacje pozarządowe, ośrodki wspierające dorosłe osoby z niepełnosprawnością intelektualną.

Czy to działa: Innowacja wpłynęła na zwiększenie dostępności turystycznej w odniesieniu do osób z niepełnosprawnością intelektualną, zachęciła osoby z niepełnosprawnością intelektualną do samodzielnego podróżowania i poprawiła ich pewność siebie w tym zakresie. Testy wykazały, że przewodniki, w bardzo atrakcyjny dla podróżnika sposób, wyposażają go w konkretne umiejętności i zasób wiedzy potrzebny do jak najbardziej samodzielnego i pełnego uczestnictwa w życiu publicznym poprzez korzystanie z przestrzeni publicznej.

Autorzy: Sylwia Ciszewska, Marta Wiśniewska-Żygo

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Rozwiązanie stanowi komplet przewodników turystycznych, które zostały przystosowane do potrzeb osób z niepełnosprawnością intelektualną w stopniu lekkim i umiarkowanym. Zawarte w nich informacje będą w formie „easy to read”, opisując kompleksowo po dwa warianty tras turystycznych w trzech polskich miastach.',
        ARRAY['type:innovation', 'area:niepelnosprawnosc', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'dostepna-szermierka',
        'Dostępna szermierka',
        'Problem: Innowacja dotyczy utrudnionego dostępu do nowoczesnego sprzętu do szermierki na wózkach - obecnie funkcjonujący jest archaiczny, ciężki, kosztowny w obsłudze i wymaga asysty osób trzecich.

Rozwiązanie: Platforma szermiercza wyróżniająca się na tle innych rozwiązań przede wszystkim samowystarczalnością zawodników (przypinanie wózków, zmiana pozycji zawodników, ustawianie odległości między zawodnikami), wagą która pozwala na łatwy transport oraz nowoczesnym, niezawodnym systemem mocowań wózków (również w czasie zawodów sportowych).

Dla kogo: Zawodniczki i zawodnicy uprawiające/ uprawiający szermierkę na wózkach, zarówno na poziomie rekreacyjnym, jak i zawodnicy startujący w turniejach.

Kto może skorzystać: Kluby sportowe i organizacje zajmujące się organizacją treningów i zawodów dla osób poruszajacych się na wózkach

Czy to działa: Prototyp, który powstał na etapie testu innowacji spełnia większość pierwotnych założeń innowacji, nie osiągnął jednak formy na tyle dojrzałej, by rekomendować jego stosowanie w obecnym kształcie. Obecne projekty techniczne zebrane w ramach specyfikacji technicznej prototypu, umożliwiają wyprodukowanie platformy przez niemal każdy zainteresowany podmiot (klub sportowy, stowarzyszenie, fundację, grupę potencjalnych użytkowników), ale wysiłek związany z taką pracą – przede wszystkim organizacyjny – dla większości użytkowników przekracza zysk związany z posiadaniem platformy szermierczej do własnej, wyłącznej dyspozycji. Nie udało się doprowadzić do pełnej samoobsługi platformy, przez zawodnika poruszającego się na wózku. Rozwiązanie jest obiecujące wymaga jednak dalszego rozwoju.

Autorzy: Fundacja Centrum Inicjatyw Sportowych

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Platforma szermiercza wyróżniająca się na tle innych rozwiązań przede wszystkim samowystarczalnością zawodników (przypinanie wózków, zmiana pozycji zawodników, ustawianie odległości między zawodnikami), wagą która pozwala na łatwy transport oraz nowoczesnym, niezawodnym systemem mocowań wózków (również w czasie zawodów sportowych).',
        ARRAY['type:innovation', 'area:niepelnosprawnosc', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'dostepny-stol-targowy',
        'Dostępny stół targowy',
        'Problem: Innowacja odpowiada na trudności w robieniu codziennych zakupów występujące wśród osób ze specjalnymi potrzebami.

Rozwiązanie: Innowacja polega na opracowaniu specjalnego stołu targowego, który dzięki udogodnieniom staje się dostępny dla osób starszych i niepełnosprawnych, usprawniając czy też umożliwiając proces robienia zakupów na targowisku. W ramach innowacji powstały cztery warianty stołu, które posiadają takie rozwiązania jak m.in.: odpowiednie nachylenie blatu; uchwyty do zawieszenia torby, kuli, laski; bilownice na monety; poręcze; dodatkowe półki pod stołem; dodatkowe wysuwane półki; krzesło/siedzisko.

Dla kogo: Osoby starsze, osoby z niepełnosprawnościami, osoby poruszające się o kulach ortopedycznych, z balkonikami, osoby z zaburzeniami równowagi, z ograniczoną sprawnością ruchową kończyn górnych, z zaburzoną motoryką dłoni i palców, używające ortez, poruszające się na wózkach inwalidzkich

Kto może skorzystać: Podmioty będące właścicielami targowisk, urzędy gmin, jednostki edukacyjne, kulturalne

Czy to działa: Innowacja zaspokaja potrzebę społeczną - wyraźnie ułatwia kupowanie produktów na targu. Traktując jednak proces robienia zakupów nieco szerzej, należałoby również wziąć pod uwagę dojazd na targ i poruszanie się po przestrzeni targowiska., co jak się okazuje stanowi podstawową barierę dla klientów z trudnościami w zakresie mobilności. Bez zapewnienia beneficjentom dostępnego transportu na targ czy instruktażu jak korzystać ze stołów, rozwiązanie, pomimo wysokiego potencjału, może osiągnąć niski bilans użyteczności.

Autorzy: Gmina Miasta Dębica

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Innowacja polega na opracowaniu specjalnego stołu targowego, który dzięki udogodnieniom staje się dostępny dla osób starszych i niepełnosprawnych, usprawniając czy też umożliwiając proces robienia zakupów na targowisku. W ramach innowacji powstały cztery warianty stołu, które posiadają takie rozwiązania jak m.in.: odpowiednie nachylenie blatu; uchwyty do zawieszenia torby, kuli, laski; bilownice na monety; poręcze; dodatkowe półki pod stołem; dodatkowe wysuwane półki; krzesło/siedzisko.',
        ARRAY['type:innovation', 'area:niepelnosprawnosc', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'dostepny-transport-publiczny',
        'Dostępny transport publiczny',
        'Problem: Innowacja odpowiada na utrudniony dostęp do komunikacji miejskiej osób z dysfunkcją narządu wzroku i brak dostępu do informacji pasażerskiej.

Rozwiązanie: Innowację stanowi aplikacja mobilna „Dostępny Transport Publiczny” będąca przeniesieniem aplikacji "Zaraz jadę" z systemu iOS na Android. Jest ona dedykowana osobom niewidomym i słabowidzącym i pozwala na bezpieczne, komfortowe i bezproblemowe korzystanie z komunikacji miejskiej. Aplikacja została wyposażona w takie funkcje jak m.in. wyświetlanie przystanków na mapie (wraz z opisem infrastruktury przystankowej), zaznaczanie na mapie położenia pojazdów komunikacji miejskiej wraz z animacją zmiany lokalizacji, wyznaczanie trasy do wybranego przystanku z uwzględnieniem bieżącej sytuacji ruchowej, wsparcie dla funkcji dostępności TalkBack.

Dla kogo: Osoby z dysfunkcją narządu wzroku, osoby, które regularnie korzystają z komunikacji miejskiej w Warszawie.

Kto może skorzystać: Przedstawiciele Warszawskiego Transportu Publicznego, opiekunowie i bliscy osób z zaburzeniami wzroku, ośrodki wspierające osoby z zaburzeniami widzenia.

Czy to działa: Rozwiązanie zostało pozytywnie ocenione przez członków grupy testującej choć część osób z uwagi na przyzwyczajenie do obecnie stosowanych narzędzi wyrażała się sceptycznie. Grantobiorca sygnalizował trudności w zakresie korzystania w działalności aplikacji z danych pochodzących ze zintegrowanych systemów zarządców komunikacji miejskiej co jednak nie przekładało się na odczucia testerów. W trakcie testów zgłoszono liczne rekomendacje do usprawnienia działalności aplikacji m.in. w zakresie zapewnienia bieżącej aktualizacji informacji na temat infrastruktury przystankowej, poprawności gramatycznej i skrótowego odczytywanych komunikatów czy zapewnienia funkcjonalności aplikacji również na starsze wersje systemu Android.

Autorzy: Piotr Jeremicz

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Innowację stanowi aplikacja mobilna „Dostępny Transport Publiczny” będąca przeniesieniem aplikacji "Zaraz jadę" z systemu iOS na Android. Jest ona dedykowana osobom niewidomym i słabowidzącym i pozwala na bezpieczne, komfortowe i bezproblemowe korzystanie z komunikacji miejskiej. Aplikacja została wyposażona w takie funkcje jak m.in. wyświetlanie przystanków na mapie (wraz z opisem infrastruktury przystankowej), zaznaczanie na mapie położenia pojazdów komunikacji miejskiej wraz z animacją zmiany lokalizacji, wyznaczanie trasy do wybranego przystanku z uwzględnieniem bieżącej sytuacji ruchowej, wsparcie dla funkcji dostępności TalkBack.',
        ARRAY['type:innovation', 'area:niepelnosprawnosc', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'dostepny-wniosek-dla-ggluchych',
        'Dostępny wniosek dla g/Głuchych',
        'Problem: Innowacja odpowiada na problemy i potrzeby osób głuchych, takie jak: brak szybkiej ścieżki dostępu do usługi tłumaczenia w instytucjach publicznych, brak formalnych dokumentów zrozumiałych dla g/Głuchych chcących załatwić sprawę urzędową i w efekcie konieczność wypełniania dokumentów w języku polskim (obcym dla g/Głuchych) np. w celu zapewnienia sobie tłumacza PJM do konkretnej sprawy urzędowej w instytucjach publicznych.

Rozwiązanie: W ramach innowacji opracowano i przetestowano 3 wzory dokumentów urzędowych będących wnioskami o zapewnienie dostępności w określonym obszarze usług publicznych. Rozwiązanie ma na celu ułatwienie osobom g/Głuchym przejście przez urzędowe procedury, w placówkach nie zapewniających natychmiastowego wsparcia tłumacza polskiego języka migowego.

Dla kogo: Osoby g/Głuche i niedosłyszące posługujące się Polskim Językiem Migowym

Kto może skorzystać: Podmioty administracji publicznej, jednostki prywatne oraz organizacje pozarządowe wspierające dostępność dla osób g/Głuchych.

Czy to działa: Materiały przygotowane w ramach projektu w opinii testerów są wysoko przydatnymi i efektywnymi produktami. Wypracowane rozwiązanie zwiększa dostęp do samodzielnego zgłoszenia zapotrzebowania na tłumacza. Należy natomiast zauważyć, że użycie może być w pewnym stopniu ograniczone do osób, które znają określone znaki lub symbole. Dla niektórych konieczne będzie dodatkowe wytłumaczenie lub definicje, co z kolei wpływa ujemnie na skuteczność rozwiązania. Potrzeby osób Głuchych zostaną zaspokojone natomiast pod warunkiem szerokiego dostępu do wniosków: wprowadzenie wniosków przez instytucje do swoich działań/procedur; widoczne mieszczenie wniosków na stronach instytucji; świadomości grupy docelowej , że takie wnioski istnieją. Przy spełnieniu tych warunków dostosowany wniosek mógłby stanowić swoistą “szybką ścieżkę dostępu” do dalszych usług dostosowanych do potrzeb Głuchych (do tłumacza lub tłumaczenia).

Autorzy: Małgorzata Talipska

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'W ramach innowacji opracowano i przetestowano 3 wzory dokumentów urzędowych będących wnioskami o zapewnienie dostępności w określonym obszarze usług publicznych. Rozwiązanie ma na celu ułatwienie osobom g/Głuchym przejście przez urzędowe procedury, w placówkach nie zapewniających natychmiastowego wsparcia tłumacza polskiego języka migowego.',
        ARRAY['type:innovation', 'area:niepelnosprawnosc', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'drogowskazy-ajkum',
        'Drogowskazy AJKUM',
        'Problem: Innowacja stanowi odpowiedź na utrudnioną orientację pacjentów onkologicznych w złożonej architekturze budynków jednostek medycznych (z wieloma zaułkami, przejściami i windami), która może prowadzić do dezorientacji i trudności w odnalezieniu odpowiednich pomieszczeń.

Rozwiązanie: System nawigacji po centrum leczenia specjalistycznego, np. onkologicznego opierający się na sieci check pointów (nie wymagający instalacji na telefonie użytkownika). Za pomocą dedykowanej aplikacji wskazują drogę do siebie nawzajem nawigując pacjenta „krok po kroku” do wybranego miejsca docelowego. Dzięki niemu, pacjenci i użytkownicy o obniżonej percepcji spowodowanej chorobą, wiekiem czy brakiem osoby towarzyszącej będą w stanie poruszać się po budynku i bez problemu odnajdować interesujące ich pomieszczenia.

Dla kogo: Innowacja kierowana jest do pacjentów chorujący onkologicznie, których percepcja ze względu na proces chorobowy i leczniczy jest znacząco obniżona.

Kto może skorzystać: Centrum specjalistycznego leczenia onkologicznego, szpitale, przychodnie.

Czy to działa: Testy przeprowadzone w projekcie częściowo dowiodły skuteczności interwencji. Zaobserwowano, że spełnione są założenia obejmujące prawidłowe i skuteczne prowadzenie pacjentów do wybranych w teście miejsc, pacjenci są w stanie samodzielnie korzystać z urządzeń bez konieczności wcześniejszego szkolenia oraz mają poczucie skuteczności systemu nawigacji w prowadzeniu ich docelowego miejsca. Jednocześnie, niski stopień „pokrycia” terenu szpitala urządzeniami, krótki czas testowania oraz stan zdrowia pacjentów, sprawił, że nie można jednoznacznie stwierdzić czy system takiej nawigacji wywołuje oczekiwane w grupie docelowej zmiany tj. ograniczenie konieczności korzystania z pomocy osób trzecich, ułatwienie szybkiej i sprawnej komunikacji między różnymi punktami szpitala, a w efekcie zwiększenie komfortu i poczucia bezpieczeństwa pacjentów wynikającego z łatwego w obsłudze systemu wspierającego komunikację po placówce.

Autorzy: Fundacja Ajkum im. Anny i Józefa Kumorek

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'System nawigacji po centrum leczenia specjalistycznego, np. onkologicznego opierający się na sieci check pointów (nie wymagający instalacji na telefonie użytkownika). Za pomocą dedykowanej aplikacji wskazują drogę do siebie nawzajem nawigując pacjenta „krok po kroku” do wybranego miejsca docelowego. Dzięki niemu, pacjenci i użytkownicy o obniżonej percepcji spowodowanej chorobą, wiekiem czy brakiem osoby towarzyszącej będą w stanie poruszać się po budynku i bez problemu odnajdować interesujące ich pomieszczenia.',
        ARRAY['type:innovation', 'area:zdrowie', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'e-rzecznik-konsumenta-seniora',
        'E-rzecznik konsumenta seniora',
        'Problem: Innowacja odpowiada na problem niedostatecznej liczby narzędzi pomocy konsumenckiej skierowanych do osób starszych, którzy jako grupa szczególnie narażona na nieuczciwe praktyki przedsiębiorców potrzebują skierowanego bezpośrednio do nich i uwzględniającego ich potrzeby wsparcia narzędzia.

Rozwiązanie: Aplikacja umożliwiająca seniorom w prosty i intuicyjny sposób otrzymanie szybkiej, rzetelnej i konkretnej porady prawnej z zakresu wybranych zagadnień prawa konsumenckiego, z którymi konsumenci-seniorzy mają najczęściej problemy (m.in. w zakresie składania reklamacji, odstąpienia od umowy czy egzekwowania przysługujących im praw konsumenckich).

Dla kogo: Osoby starsze

Kto może skorzystać: Organizacje pozarządowe zajmujące się prawami konsumentów, rzecznicy praw konsumenta przy podmiotach publicznych, takich jak Urząd Miasta, Urząd Gminy, Starostwo Powiatowe itp., Urząd Ochrony Praw Konsumenta, Rzecznik Praw Obywatelskich, Centra Aktywności Seniorów, Miejskie Dzienne Domy Pomocy Społecznej.

Czy to działa: Aplikacja została wysoko oceniona przez testerów. Należy jednak pamiętać, że była to grupa osób, które posiadają wysoki kapitał społeczny, co z pewnością warunkuje ocenę skuteczności efektów. Dużym atutem aplikacji w opinii testerów był łatwy język, intuicyjna nawigacja oraz dostępny interfejs. Główną barierą wydaje się być brak zaufania znacznej części osób 65+ do aplikacji jako takich, brak nawyku ich używania/instalowania oraz niechęć do rezygnacji z konsultacji osobistych.

Autorzy: Stowarzyszenie Ochrony Konsumentów Aquila

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Aplikacja umożliwiająca seniorom w prosty i intuicyjny sposób otrzymanie szybkiej, rzetelnej i konkretnej porady prawnej z zakresu wybranych zagadnień prawa konsumenckiego, z którymi konsumenci-seniorzy mają najczęściej problemy (m.in. w zakresie składania reklamacji, odstąpienia od umowy czy egzekwowania przysługujących im praw konsumenckich).',
        ARRAY['type:innovation', 'area:seniorzy', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'edki-kredki-terapeutyczne',
        'Edki - kredki terapeutyczne',
        'Problem: Zestaw kredek terapeutycznych dla dzieci ze spastycznością kończyny górnej. Dzięki specjalnemu kształtowi, mobilizują i aktywizują dłoń, palce, nadgarstek i łokieć do wyprostu zamiast zamykania i wspierają aktywną terapię przez zabawę.

Rozwiązanie: Zestaw kredek terapeutycznych dla dzieci ze spastycznością kończyny górnej. Dzięki specjalnemu kształtowi, mobilizują i aktywizują dłoń, palce, nadgarstek i łokieć do wyprostu zamiast zamykania i wspierają aktywną terapię przez zabawę.

Dla kogo: Dzieci ze spastycznością kończyny górnej

Kto może skorzystać: Rehabilitanci, rodzice i opiekunowie dzieci ze spastycznością kończyny górnej, nauczyciele wychowania przedszkolnego, wczesnoszkolnego i szkolnego.

Czy to działa: Kredki skutecznie wspomagają fizjoterapię spastycznych dłoni, umożliwiają dzieciom działania twórcze, podnoszą poczucie sprawczości i samodzielności oraz uczą prawidłowego chwytu pisarskiego umożliwiając aktywną terapię przez zabawę.

Autorzy: dr Aleksandra Satława

Program: INKUBATOR WŁĄCZENIA SPOŁECZNEGO

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Zestaw kredek terapeutycznych dla dzieci ze spastycznością kończyny górnej. Dzięki specjalnemu kształtowi, mobilizują i aktywizują dłoń, palce, nadgarstek i łokieć do wyprostu zamiast zamykania i wspierają aktywną terapię przez zabawę.',
        ARRAY['type:innovation', 'area:rodzina-i-piecza-zastepcza', 'source:rops-biblioteka']::text[],
        '',
        'https://www.youtube.com/watch?v=ev173g-d_vA',
        'published'
    ),
    (
        'edu-gra-hahaha',
        'Edu gra HaHaHa',
        'Problem: Innowacja odpowiada na brak narzędzi umożliwiających podtrzymanie dobrej kondycji psychicznej osób z niepełnosprawnościami oraz osób starszych oraz brak szerokiego dostępu do łagodnej rehabilitacji, jaką jest joga śmiechu.

Rozwiązanie: Innowację stanowi integracyjna gra planszowa, ucząca wykorzystania jogi śmiechu w integracji i podtrzymywaniu dobrej kondycji psychicznej osób starszych i z niepełnosprawnościami. Gra składa się z pudełka, planszy, 53 kart w formie fiszek oraz pionka. Karty do gry zostały podzielone na 4 usystematyzowane podstawowe rodzaje ćwiczeń: rozgrzewających, śmiechowych, integrujących i oddechowych według zasady przeprowadzania sesji jogi śmiechu. Przygotowana w ramach innowacji gra nie będzie tradycyjną grą, ponieważ nie wyłania ona wygranych i przegranych. Jej celem jest integracja grupy, a także podniesienie poziomu energii.

Dla kogo: Osoby starsze o ograniczonej mobilności i percepcji, osoby z niepełnosprawnością intelektualną.

Kto może skorzystać: Organizacje pozarządowe, podmioty pracujące z osobami starszymi i z osobami z niepełnosprawnością (np. Warsztaty Terapii Zajęciowej, szkoły specjalne).

Autorzy: Katarzyna Ziętek

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Innowację stanowi integracyjna gra planszowa, ucząca wykorzystania jogi śmiechu w integracji i podtrzymywaniu dobrej kondycji psychicznej osób starszych i z niepełnosprawnościami. Gra składa się z pudełka, planszy, 53 kart w formie fiszek oraz pionka. Karty do gry zostały podzielone na 4 usystematyzowane podstawowe rodzaje ćwiczeń: rozgrzewających, śmiechowych, integrujących i oddechowych według zasady przeprowadzania sesji jogi śmiechu. Przygotowana w ramach innowacji gra nie będzie tradycyjną grą, ponieważ nie wyłania ona wygranych i przegranych. Jej celem jest integracja grupy, a także podniesienie poziomu energii.',
        ARRAY['type:innovation', 'area:seniorzy', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'ev-modul-do-wozkow-inwalidzkich',
        'EV moduł do wózków inwalidzkich',
        'Problem: Innowacja jest odpowiedzią na trudności w samodzielnym poruszaniu się na wózku osób z niepełnosprawnościami i problemy z jazdą pod górę osób na wózkach.

Rozwiązanie: W ramach innowacji powstał prototyp modułu elektrycznego do wózka inwalidzkiego, który wyposażony jest w dwa koła (przednie i tylne). Dzięki takiemu rozwiązaniu zwiększa się stabilność wózka, szczególnie podczas jazdy pod górę i po chodnikach. Równocześnie wymiary wózka zwiększają się nie więcej niż o 10%.

Dla kogo: Osoby, które z powodów zdrowotnych poruszają się na wózkach

Kto może skorzystać: Producenci wózków inwalidzkich, szpitale, ośrodki rehabilitacyjne.

Czy to działa: Innowacja przyczyniła się do wzrostu wygody związanej z codziennym poruszaniem się na wózku inwalidzkim. Użytkownicy wózków potwierdzili, że po zainstalowaniu opracowanego modułu łatwiej jest im się poruszać po chodniku, a także podjeżdżać pod wzniesienia.

Autorzy: Ivan Atamanchuk, Volodymyr Atamanchuk

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'W ramach innowacji powstał prototyp modułu elektrycznego do wózka inwalidzkiego, który wyposażony jest w dwa koła (przednie i tylne). Dzięki takiemu rozwiązaniu zwiększa się stabilność wózka, szczególnie podczas jazdy pod górę i po chodnikach. Równocześnie wymiary wózka zwiększają się nie więcej niż o 10%.',
        ARRAY['type:innovation', 'area:niepelnosprawnosc', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'glucha-ankieta',
        'Głucha ankieta',
        'Problem: Innowacja odpowiada na brak możliwości wypowiadania się przedstawicieli społeczności osób g/Głuchych w badaniach ankietowych i brak możliwości przeprowadzania badań ankietowych dla osób pragnących uwzględnić w badaniu osoby z dysfunkcją słuchu.

Rozwiązanie: Kod źródłowy wtyczki do zainstalowania w LimeSurvey (internetowy system ankietujący). Kod ten umożliwia bezpośrednie nagrywanie i przesyłanie odpowiedzi video w polskim języku migowym w co najmniej jednym rodzaju pytań. Innowacja została stworzona (napisana) z wykorzystaniem dostępnych bibliotek i API (Application Programming Interface) oraz przystosowana do potrzeb g/Głuchych z uwzględnieniem możliwości programu LimeSurvey. Jeśli badacz założył, że w badaniu wezmą udział użytkownicy PJM i zainstalował wypracowaną wtyczkę, osoby g/Głuche mogą odpowiedzieć na pytanie w języku migowym za pomocą kamery w swoim laptopie czy telefonie.

Dla kogo: Osoby g/Głuche, badacze, którzy chcą ująć w swoich wynikach użytkowników PJM.

Kto może skorzystać: Badacze indywidualni, uczelnie wyższe i środowiska akademickie, instytuty badawcze.

Czy to działa: Wdrożenie innowacji umożliwiło osobom ze społeczności g/Głuchych wypowiadanie swojego zdania w internetowym systemie ankietującym. Z kolei badacze zyskali możliwość poznania ich opinii w szeregu różnych tematów. Głucha ankieta umożliwiła wypowiedzenie się w swoim języku osobom g/Głuchym nie tylko na komputerach, ale także na urządzeniach mobilnych w każdym miejscu, które uznają za stosowne. Łatwość i intuicyjność obsługi wtyczki powoduje, że nie trzeba specjalnego przeszkolenia z jej obsługi.

Autorzy: Instytut Spraw Głuchych

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Kod źródłowy wtyczki do zainstalowania w LimeSurvey (internetowy system ankietujący). Kod ten umożliwia bezpośrednie nagrywanie i przesyłanie odpowiedzi video w polskim języku migowym w co najmniej jednym rodzaju pytań. Innowacja została stworzona (napisana) z wykorzystaniem dostępnych bibliotek i API (Application Programming Interface) oraz przystosowana do potrzeb g/Głuchych z uwzględnieniem możliwości programu LimeSurvey. Jeśli badacz założył, że w badaniu wezmą udział użytkownicy PJM i zainstalował wypracowaną wtyczkę, osoby g/Głuche mogą odpowiedzieć na pytanie w języku migowym za pomocą kamery w swoim laptopie czy telefonie.',
        ARRAY['type:innovation', 'area:niepelnosprawnosc', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'gluchy-czytelnik-w-bibliotece',
        'Głuchy czytelnik w bibliotece',
        'Problem: Innowacja jest odpowiedzią na potrzebę włączenia osób g/Głuchych do społeczności czytelników korzystających z usług bibliotek.

Rozwiązanie: Publikacja przybliżająca osobom g/Głuchym instytucję jaką jest biblioteka oraz pokazująca, że czytanie jest ważne. Publikacja powstała w polskim języku migowym, a następnie została przełożona na łatwy tekst w języku polskim. Publikacja daje wskazówki jak wspierać dziecko w czytaniu i jak korzystać z biblioteki.

Dla kogo: Osoby g/Głuche, szczególnie rodzice, którzy posiadają dzieci w wieku szkolnym, zarówno słyszące (KODA), jak i dzieci g/Głuche oraz słabosłyszące.

Kto może skorzystać: Biblioteki publiczne, biblioteki szkolne, szkoły integracyjne.

Czy to działa: Publikacja ułatwia osobom g/Głuchym dostęp do bibliotek, wyjaśnia sposób ich działania i mobilizuje do korzystania z nich. Może realnie wpłynąć na jakość życia g/Głuchych rodziców, a przede wszystkim ich dzieci.

Autorzy: dr Dominika Wiśniewska, Anna Antos

Program: INKUBATOR WŁĄCZENIA SPOŁECZNEGO

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Publikacja przybliżająca osobom g/Głuchym instytucję jaką jest biblioteka oraz pokazująca, że czytanie jest ważne. Publikacja powstała w polskim języku migowym, a następnie została przełożona na łatwy tekst w języku polskim. Publikacja daje wskazówki jak wspierać dziecko w czytaniu i jak korzystać z biblioteki.',
        ARRAY['type:innovation', 'area:niepelnosprawnosc', 'source:rops-biblioteka']::text[],
        '',
        'https://www.youtube.com/watch?v=BoAC-J1Owr4',
        'published'
    ),
    (
        'go-ahead-mow-smialo',
        'Go ahead - mów śmiało!',
        'Problem: Innowacja jest odpowiedzią na trudności w komunikowaniu się dorosłych i młodzieży z niepełnosprawnością intelektualną oraz problemy w nawiązywaniu bliższych relacji interpersonalnych;

Rozwiązanie: Innowację stanowi aplikacja rozwijająca umiejętności komunikacyjne osób z niepełnosprawnością intelektualną. Bazuje ona na lekcjach tematycznych oraz quizach, podczas których użytkownik wybiera komunikat zwrotny do przedstawionej sytuacji społecznej i otrzymuje konsekwencję stworzonej interakcji w formie określonej „mimiki” uczestnika rozmowy.

Dla kogo: Młodzież z niepełnosprawnością intelektualną i osoby dorosłe z niepełnosprawnością intelektualną.

Kto może skorzystać: Warsztaty Terapii Zajęciowej, szkoły integracyjne i specjalne, organizacje pozarządowe wspierające osoby z niepełnosprawnością intelektualną.

Czy to działa: Rozwiązanie nie sprawdziło się w praktyce. W trakcie prac nad aplikacją okazało się niemożliwym (w proponowanym budżecie i dostępnych w posiadaniu Innowatora na dany moment zasobach) wprowadzenie systemu odczytu i przetwarzania mimiki uczestnika interakcji. Wobec tego zdecydowano o podjęciu próby zastąpienia tego ustandaryzowanymi formami mimiki np. emotikonów, które w założeniu miały odzwierciedlać w schematyczny sposób reakcję użytkowników. Narzędzie w takiej formie zostało dobrze przyjęte przez grupę testującą, chętnie korzystali z aplikacji – terapeuci również. Nie zauważono jednak znaczącego wpływu narzędzia na wzmocnienie kompetencji komunikacyjnych grupy testującej. Ponadto, aplikacja, w pełni samodzielnie, może być wykorzystywana tylko przez osoby z opanowaną techniką czytania ze zrozumieniem. Niektóre osoby testujące miały trudność w zrozumieniu pojęć dla nich abstrakcyjnych takich jak: aplikacja, logowanie, login itp. Dla niektórych z osób konieczne było indywidualne wsparcie opiekuna, (zwłaszcza na etapie wdrażania do obsługi urządzenia).

Autorzy: Stowarzyszenie „Radość” w Dębicy

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Innowację stanowi aplikacja rozwijająca umiejętności komunikacyjne osób z niepełnosprawnością intelektualną. Bazuje ona na lekcjach tematycznych oraz quizach, podczas których użytkownik wybiera komunikat zwrotny do przedstawionej sytuacji społecznej i otrzymuje konsekwencję stworzonej interakcji w formie określonej „mimiki” uczestnika rozmowy.',
        ARRAY['type:innovation', 'area:niepelnosprawnosc', 'source:rops-biblioteka']::text[],
        '',
        'https://www.youtube.com/watch?v=m5uEjEV0eDY',
        'published'
    ),
    (
        'gra-o-zdrowie',
        'Gra o zdrowie',
        'Problem: Innowacja odpowiada na ograniczony zasób rynku gier terapeutycznych dla osób w kryzysie psychicznym, zwłaszcza dotyczących zagadnień związanych z funkcjonowaniem rynku pracy. Równocześnie dostęp do zajęć terapeutycznych oswajających i przygotowujących do podjęcia (niekiedy powtórnego) zatrudnienia jest jednym z kluczowych aspektów zdrowienia pacjentów, gdyż niejednokrotnie podjęcie zatrudnienia chroni ich przed ponownym pojawieniem się kryzysu psychicznego.

Rozwiązanie: Terapeutyczna gra planszowa, która wymaga od gracza zaangażowania, wcielania się w różne postaci z obszaru rynku pracy (np. pracownik, pracodawca, kandydat), pozwala odkryć jego potencjał i przygotować się do zmierzenia z realnymi aspektami rynku pracy przed podjęciem rzeczywistych działań.

Dla kogo: Osoby doświadczające kryzysu psychicznego (w szczególności mowa o pacjentach z doświadczeniem psychozy, objawami zaburzeń psychotycznych i zaburzeniami nastroju), powracające na rynek pracy.

Kto może skorzystać: Jednostki wspierające osoby doświadczające kryzysów psychicznych (np. oddziały dzienne), środowiskowe domy samopomocy, kluby pacjenta ale także szkoły publiczne, prywatne przygotowujące młode osoby do wejścia na rynek pracy, Ochotnicze Hufce Pracy, Wojewódzkie Urzędy Pracy.

Czy to działa: Rozwiązanie zostało docenione z uwagi na prostotę i łatwość użytkowania oraz możliwość podziału jednej rozgrywki na kilka spotkań. Często osoby doświadczające kryzysu psychicznego, nie są w stanie przez dłuższy czas skupić się na grze, w związku z czym możliwość rozegrania tylko jej części jest dużą zaletą. Granie w grę przełożyło się także na wzrost wiedzy dotyczącej regulacji, zasad i praw rządzących rynkiem pracy, bardziej otwartą postawę wobec sytuacji z jakimi mogą się zetknąć na rynku pracy i poszerzenie umiejętności radzenia sobie trudnościami.

Autorzy: Paulina Dąbrowska

Program: INKUBATOR DOSTĘPNOŚCI

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Terapeutyczna gra planszowa, która wymaga od gracza zaangażowania, wcielania się w różne postaci z obszaru rynku pracy (np. pracownik, pracodawca, kandydat), pozwala odkryć jego potencjał i przygotować się do zmierzenia z realnymi aspektami rynku pracy przed podjęciem rzeczywistych działań.',
        ARRAY['type:innovation', 'area:zdrowie', 'source:rops-biblioteka']::text[],
        '',
        'https://www.youtube.com/watch?v=YRzg98fveHc',
        'published'
    ),
    (
        'health-guide-pl',
        'Health Guide PL',
        'Problem: Innowacja odpowiada na utrudniony dla Obcokrajowców (osób niepolskojęzycznych) dostęp do publicznego systemu opieki zdrowotnej w Polsce mimo zgłoszenia do powszechnego ubezpieczenia zdrowotnego.

Rozwiązanie: Innowacją społeczną jest przewodnik w języku angielskim i języku ukraińskim po systemie publicznej służy zdrowia w Polsce (podstawowa opieka zdrowotna) – Health Guide PL dla Obcokrajowców, przebywających w Polsce i posiadających prawo do usług w ramach polskiej publicznej opieki zdrowotnej. Przewodnik dostępny jest w formie drukowanej z pliku PDF, w formie cyfrowej w pliku PDF oraz aplikacji na urządzenia mobilne w systemie Android. Przewodnik umożliwia dostęp do uporządkowanych, zrozumiałych dla Obcokrajowca informacji i jednocześnie pozwala na zdobycie lub zwiększenie wiedzy o przysługujących pacjentom w Polsce możliwościach zaspokajania potrzeb w zakresie ochrony zdrowia.

Dla kogo: Obcokrajowcy przebywający w Polsce legalnie (na podstawie zatrudnienia, odbywania nauki i/lub statusu uchodźcy) oraz ich rodziny, zwłaszcza dzieci.

Kto może skorzystać: Obcokrajowcy (pracownicy, studenci, i/lub uchodźcy i ich rodziny którzy przebywają wraz z rodzinami w Polsce legalnie i mają prawo do bezpłatnej opieki medycznej w ramach polskiego systemu służby zdrowia), kadry administracyjne i personel polskiego systemu publicznej służby zdrowia

Czy to działa: Zakres osiągniętych efektów jest bardzo wysoki. Skatalogowanie informacji, które są bardzo rozproszone w systemie, w pigułki wiedzy dotyczące poszczególnych aspektów funkcjonowania opieki zdrowotnej w Polsce i udostępnienie językowe tych informacji okazało się skutecznym narzędziem zwiększania wiedzy cudzoziemców w zakresie przysługujących im praw i w zakresie posiadanych możliwości leczenia i profilaktyki w Polsce. Co ważne, dotyczy to obydwu grup docelowych (angielskojęzycznej i ukraińskiej). Innowacja skutecznie zwiększa także wiedzę cudzoziemców będących rodzicami o kalendarzu szczepień dzieci oraz ułatwia wybór lekarza pierwszego kontaktu. Co więcej, rozwiązanie okazało się przynosić pozytywne zmiany także dla kolejnej grupy: kadry administracyjnej i medycznej (zmniejszenie obciążenia w zakresie obsługi cudzoziemców, zwiększenie ich wiedzy o systemie opieki zdrowotnej), które wraz ze skalowaniem rozwiązania, mogą wygenerować duże zmiany w tych grupach.

Autorzy: Justyna Laskowska

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Innowacją społeczną jest przewodnik w języku angielskim i języku ukraińskim po systemie publicznej służy zdrowia w Polsce (podstawowa opieka zdrowotna) – Health Guide PL dla Obcokrajowców, przebywających w Polsce i posiadających prawo do usług w ramach polskiej publicznej opieki zdrowotnej. Przewodnik dostępny jest w formie drukowanej z pliku PDF, w formie cyfrowej w pliku PDF oraz aplikacji na urządzenia mobilne w systemie Android. Przewodnik umożliwia dostęp do uporządkowanych, zrozumiałych dla Obcokrajowca informacji i jednocześnie pozwala na zdobycie lub zwiększenie wiedzy o przysługujących pacjentom w Polsce możliwościach zaspokajania potrzeb w zakresie ochrony zdrowia.',
        ARRAY['type:innovation', 'area:integracja-cudzoziemcow', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'hear-it',
        'Hear IT',
        'Problem: Innowacja odpowiada na brak materiałów dydaktycznych do samodzielnej nauki z obszaru programowania i brak możliwości uczenia się podstaw programowania przez osoby g/Głuche.

Rozwiązanie: Internetowa platforma edukacyjna opracowana w Polskim Języku Migowym dla osób g/Głuchych pragnących wejść w branżę IT. Zawiera video-słownik z głównymi pojęciami z obszaru programowania, podręczniki dot. języków programowania takich jak Python, Java, Javascript, kursy elearningowe oraz etiudy gamingowe dając dostęp do bazowej wiedzy programistycznej w języku PJM.

Dla kogo: Osoby g/Głuche, zainteresowane kształceniem w obszarze IT.

Kto może skorzystać: Szkoły policealne, uczelnie wyższe, technika, licea, organizacje pozarządowe zajmując się aktywizacją zawodową osób g/Głuchych.

Czy to działa: Innowacja przyniosła korzyści w postaci zaznajomienia się z podstawowymi pojęciami z obszaru programowania i pozwoliła zdobyć nowe umiejętności i wiedzę, która wcześniej przez odbiorców była uznawana za zbyt trudną. Innowacja jest skutecznym pierwszym krokiem, który osoby g/Głuche mogą podjąć, aby zwiększyć swoje szanse na rynku pracy.

Autorzy: Stowarzyszenie Edukacji Pozaformalnej „Meritum”, Bartosz Kosiński, Kamila Chęcińska, Mirosław Bohatkiewicz

Program: INKUBATOR WŁĄCZENIA SPOŁECZNEGO

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Internetowa platforma edukacyjna opracowana w Polskim Języku Migowym dla osób g/Głuchych pragnących wejść w branżę IT. Zawiera video-słownik z głównymi pojęciami z obszaru programowania, podręczniki dot. języków programowania takich jak Python, Java, Javascript, kursy elearningowe oraz etiudy gamingowe dając dostęp do bazowej wiedzy programistycznej w języku PJM.',
        ARRAY['type:innovation', 'area:niepelnosprawnosc', 'source:rops-biblioteka']::text[],
        '',
        'https://www.youtube.com/watch?v=uDLOSoCb3E8',
        'published'
    ),
    (
        'himalaje-autyzmu',
        'Himalaje autyzmu',
        'Problem: Trudności w dostępie do usług i świadczeń medycznych dla osób (w tym ze spektrum autyzmu) przejawiających zachowania trudne (w tym agresywne i autoagresywne).

Rozwiązanie: Himalaje Autyzmu zostały stworzone na potrzeby wizyt w placówkach medycznych takich jak przychodnie, poradnie, punkty pobrań czy szpitale. Jest to model pracy z osobami przede wszystkim ze spektrum autyzmu), które przejawiają zachowania nieakceptowane społecznie, w tym agresywne i autoagresywne. Czterostopniowa, oparta o konkretne scenariusze postępowania metoda przygotowuje pacjenta do wizyty lekarskiej, umożliwia diagnozę schorzenia i podjęcie leczenia.

Dla kogo: Osoby dorosłe neuroatypowe (przede wszytskim ze spektrum autyzmu) przejawiające trudne zachowania nieakceptowane społeczne.

Kto może skorzystać: Placówki medyczne, szpitala, rodziny osób przejawiających trudne zachowania, asystenci osób z niepełnosprawnością, organizacje pozarządowe i podmioty zatrudniające asystentów osób z niepełnosprawnością.

Czy to działa: Innowacja jest realną i skuteczną odpowiedzią na problemy z dostępem do usług medycznych. Pozwala na zaplanowanie wizyty w taki sposób żeby zminimalizować stres związany z nowymi sytuacjami dla osób, których niestandardowe zachowanie uniemożliwia korzystanie z diagnostyki i leczenia. Pokazuje asystentom osób z niepełnosprawnościami oraz opiekunom przygotować siebie i pacjenta do różnego typu wizyt i procedur medycznych.

Autorzy: Chrześcijańskie Stowarzyszenie Osób Niepełnosprawnych, ich Rodzin i Przyjaciół „Ognisko”

Program: INKUBATOR DOSTĘPNOŚCI

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Himalaje Autyzmu zostały stworzone na potrzeby wizyt w placówkach medycznych takich jak przychodnie, poradnie, punkty pobrań czy szpitale. Jest to model pracy z osobami przede wszystkim ze spektrum autyzmu), które przejawiają zachowania nieakceptowane społecznie, w tym agresywne i autoagresywne. Czterostopniowa, oparta o konkretne scenariusze postępowania metoda przygotowuje pacjenta do wizyty lekarskiej, umożliwia diagnozę schorzenia i podjęcie leczenia.',
        ARRAY['type:innovation', 'area:zdrowie', 'source:rops-biblioteka']::text[],
        '',
        'https://www.youtube.com/watch?v=q31uQ435YAo',
        'published'
    ),
    (
        'hop-hop',
        'Hop hop - mobilny plac zabaw',
        'Problem: Innowacja jest odpowiedzią na problemy malejącej sprawności ruchowej i często występujących trudności psychoruchowych, które są coraz większym problemem wśród dzieci. Są one uwarunkowane genetycznie, społecznie i kulturowo. Wspomaganie prawidłowego rozwoju psychoruchowego, profilaktyka i dostęp do codziennej terapii są ważnym elementem w życiu dziecka w wieku przedszkolnym i jego opiekuna.

Rozwiązanie: Rozwiązanie składa się z dwóch części: zestawu meblozabawek, który umożliwia wykonywanie ćwiczeń i zabaw ruchowych. Rozwiązanie znajduje zastosowanie w przestrzeni domowej, ale także aktywizuje najmłodszych do ćwiczeń i zabaw plenerowych. Dzięki fakturze, otworom i frezowanym prowadnicom w matach oraz dodatkowym łącznikom, dzieci mogą kreować tunele, ścieżki sensoryczne, tory przeszkód, obiekty do bujania i wiele innych zabaw. Drugą cześcią są scenariusze wspomagające domową rehabilitację – zbiór wzorów zabaw i ćwiczeń zawierających opis wykonania, porady dla opiekunów dotyczących motywacji dzieci, opisu zakresu wspomagania i terapii oraz przedstawienie ćwiczeń w formie graficznej.

Dla kogo: Dzieci w wieku przedszkolnym i wczesnoszkolnym z niepełnosprawnościami ruchowymi typu: nieprawidłowe napięcie mięśniowe, obniżona zdolność motoryczna ciała, problemy przetwarzania sensorycznego w obrębie układu proprioceptywnego czy układu równowagi.

Kto może skorzystać: Rehabilitanci, fizjoterapeuci i terapeuci integracji sensorycznej oraz rodzice dzieci z niepełnosprawnością ruchową, które mają problem z obniżoną zdolnością motoryczną ciała i zaburzeniami przetwarzania sensorycznego.

Czy to działa: Dzieci, rodzice i terapeuci pozytywnie ocenili innowację. Szczególnie zwrócili uwagę na jego niewielkie gabaryty, przy jednocześnie dużej możliwości kreowania zabaw i ćwiczeń ruchowych. Okazało się, że zestawy można ze sobą łączyć, co daje dzieciom szansę skonstruowania bardziej skomplikowanych i rozbudowanych torów przeszkód oraz stwarza możliwość zabawy i terapii w grupie.

Autorzy: dr Aleksandra Satława

Program: INKUBATOR DOSTĘPNOŚCI

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Rozwiązanie składa się z dwóch części: zestawu meblozabawek, który umożliwia wykonywanie ćwiczeń i zabaw ruchowych. Rozwiązanie znajduje zastosowanie w przestrzeni domowej, ale także aktywizuje najmłodszych do ćwiczeń i zabaw plenerowych. Dzięki fakturze, otworom i frezowanym prowadnicom w matach oraz dodatkowym łącznikom, dzieci mogą kreować tunele, ścieżki sensoryczne, tory przeszkód, obiekty do bujania i wiele innych zabaw. Drugą cześcią są scenariusze wspomagające domową rehabilitację – zbiór wzorów zabaw i ćwiczeń zawierających opis wykonania, porady dla opiekunów dotyczących motywacji dzieci, opisu zakresu wspomagania i terapii oraz przedstawienie ćwiczeń w formie graficznej.',
        ARRAY['type:innovation', 'area:rodzina-i-piecza-zastepcza', 'source:rops-biblioteka']::text[],
        '',
        'https://www.youtube.com/watch?v=kE9lpr4OJPQ',
        'published'
    ),
    (
        'innotextil',
        'Innotextil',
        'Problem: Innowacja stanowi odpowiedź na trudności w dostępie do usług fizjoterapeuty (np. dla osób starszych, o ograniczonym budżecie) i tym samym ograniczenie możliwości potrzymywania efektór terapuetycznych przez osoby starsze czy osoby np. po urazach kolan.

Rozwiązanie: Innowacyjna forma odzieży oraz przypisana do niej aplikacja umożliwia użytkownikowi stałą i dyskretną kontrolę swojego ruchu oraz powiadamia go o konieczności korekty chodu w czasie rzeczywistym. Legginsy charakteryzują się sportową formą i uniwersalnym krojem oraz są dostępne w wersji damskiej i męskiej.

Dla kogo: Grupę docelową rozwiązania stanowią osoby starsze (dzięki samodzielnej rehabilitacji w warunkach domowych seniorzy mają możliwość zyskania większej niezależności i podtrzymania sprawności fizycznej) oraz osoby z organiczeniami narządu ruchu.

Kto może skorzystać: Firmy odzieżowe, placówki specjalizujące się w rehabilitacji osób starszych czy placówki medyczne.

Czy to działa: „Innotextil” może być optymalnym rozwiązaniem dla wszystkich osób, które chcą stale monitorować poziom swojej sprawności fizycznej oraz systematycznie podtrzymywać efekty rehabilitacji w codziennym życiu. Dzięki innowacji, w warunkach domowych użytkownik może mieć stałą i dyskretną kontrolę poprawnego wykonywania ćwiczeń lub możliwość korekcji popełnianych błędów w trakcie zwykłego chodu.

Autorzy: Akademia Sztuk Pięknych w Krakowie im. Jana Matejki - Wydział Form Przemysłowych, prof. dr hab. Stanisław Tabisz, dr Bożena Groborz

Program: MAŁOPOLSKI INKUBATOR INNOWACJI SPOŁECZNYCH

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Innowacyjna forma odzieży oraz przypisana do niej aplikacja umożliwia użytkownikowi stałą i dyskretną kontrolę swojego ruchu oraz powiadamia go o konieczności korekty chodu w czasie rzeczywistym. Legginsy charakteryzują się sportową formą i uniwersalnym krojem oraz są dostępne w wersji damskiej i męskiej.',
        ARRAY['type:innovation', 'area:niepelnosprawnosc', 'source:rops-biblioteka']::text[],
        '',
        'https://www.youtube.com/watch?v=ScqdHaNxYa8',
        'published'
    ),
    (
        'inteligentny-organizer-do-lekow',
        'Inteligentny organizer do leków',
        'Problem: Innowacja stanowi odpowiedź na wyzwania związane ze sprawowaniem opieki przez opiekunów rodzinnych/nieformalnych np. nad rodzicem w starszym wieku.

Rozwiązanie: Innowację stanowi inteligentne narzędzie w formie organizera na leki, wyposażonego w czujniki umożliwiające detekcję pobrania leku, system sygnalizacji świetlnej uruchamiającej się o określonej godzinie, kiedy powinien być zażyty konkretny lek oraz specjalnie opracowanej aplikacji mobilnej. Dzięki niej, opiekun posiada możliwość ustawienia określonych godzin zażywania poszczególnych leków, a w przypadku ich zażycia lub pominięcia dawki, otrzymuje stosowne powiadomienie. Narzędzie umożliwi zdalną asystę i wsparcie podopiecznych w dbaniu o swoje zdrowie.

Dla kogo: Osoby starsze (które samodzielnie zarządzają przyjmowaniem przez siebie leków przyjmowanych „na stałe” oraz posiadają umiejętność posługiwania się smartfonem) oraz ich opiekunowie (kontrolujących przyjmowanie leków przez podopiecznych).

Kto może skorzystać: Osoby prywatne, apteki, koncerny farmaceutyczne

Czy to działa: W kontekście zdefiniowanych w projekcie potrzeb opiekunów urządzenie należy uznać za wysoce użyteczne, jednak obarczone pewnymi wyzwaniami. Kluczowy jest problem zdolności osób korzystających z urządzenia do jego montażu oraz późniejszej obsługi (np. w przypadku błędów). Koniecznym jest również poprowadzenie dalszych prac w celu zapewnienia bezawaryjnego działania urządzenia (wszelkie problemy pojawiające się na etapie testowania prototypu obniżały zaufanie do innowacji i motywację do korzystania), co oznacza konieczność prowadzenia asysty technicznej urządzeń.

Autorzy: Krzysztof Lingo, Wojciech Sójka

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Innowację stanowi inteligentne narzędzie w formie organizera na leki, wyposażonego w czujniki umożliwiające detekcję pobrania leku, system sygnalizacji świetlnej uruchamiającej się o określonej godzinie, kiedy powinien być zażyty konkretny lek oraz specjalnie opracowanej aplikacji mobilnej. Dzięki niej, opiekun posiada możliwość ustawienia określonych godzin zażywania poszczególnych leków, a w przypadku ich zażycia lub pominięcia dawki, otrzymuje stosowne powiadomienie. Narzędzie umożliwi zdalną asystę i wsparcie podopiecznych w dbaniu o swoje zdrowie.',
        ARRAY['type:innovation', 'area:zdrowie', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'jezykolamacz',
        'Językołamacz',
        'Problem: Innowacja odpowiada na trudności w komunikacji niewerbalnej dzieci z autyzmem, tzn. w rozumieniu i stosowaniu gestów, wyrazów twarzy lub nawiązywaniu kontaktu wzrokowego.

Rozwiązanie: "Językołamacz" składa się aplikacja wykorzystującej rozszerzoną rzeczywistość, która wspomaga rozwój mowy języka polskiego u dzieci w spektrum autyzmu w wieku 3–10 lat, a także instrukcja użytkowania aplikacji wraz ze scenariuszami możliwych zajęć w domu lub u terapeuty. Aplikacja przeznaczona jest dla dzieci ze spektrum autyzmu, które mają w pełni rozwinięty zmysł słuchu, ale mają zaburzony rozwój ośrodków mowy w mózgu lub inne zmiany biochemiczne w mózgu utrudniające naukę mowy w sposób naturalny.

Dla kogo: Dzieci w wieku 3-10 lat ze spektrum autyzmu borykające się z małym zasobem słownictwa, z komunikacją z opiekunami, z artykułowaniem swoich potrzeb i komunikacją z rówieśnikami.

Kto może skorzystać: Rodzice i opiekunowie prawni grupy odbiorców, pedagodzy i logopedzi, które będą wykorzystywać rozwiązanie podczas zajęć z grupą odbiorców, szkoły specjalne i integracyjne, placówki wspomagające terapię osób ze spektrum.

Czy to działa: Aplikacja spotkała się z dużą aprobatą zarówno rodziców testujących ją z dziećmi w warunkach domowych jak i nauczycieli czy terapeutów pracujących z grupami w wieku wczesnoszkolnym podczas zajęć rozwojowo- wspierających w placówkach edukacyjnych. Wykorzystanie medium jakim jest urządzenie mobilne (smartfon/tablet) wpłynęło na skuteczność dotarcia do tej grupy docelowej.

Autorzy: Stowarzyszenie Edukacja Praktyczna TKK

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        '"Językołamacz" składa się aplikacja wykorzystującej rozszerzoną rzeczywistość, która wspomaga rozwój mowy języka polskiego u dzieci w spektrum autyzmu w wieku 3–10 lat, a także instrukcja użytkowania aplikacji wraz ze scenariuszami możliwych zajęć w domu lub u terapeuty. Aplikacja przeznaczona jest dla dzieci ze spektrum autyzmu, które mają w pełni rozwinięty zmysł słuchu, ale mają zaburzony rozwój ośrodków mowy w mózgu lub inne zmiany biochemiczne w mózgu utrudniające naukę mowy w sposób naturalny.',
        ARRAY['type:innovation', 'area:rodzina-i-piecza-zastepcza', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'kaski-binauralne',
        'Kaski binauralne',
        'Problem: Innowacja odpowiada na nieodpowiedni poziom rehabilitacji osób tracących wzrok (rehabilitacja nie dość bezpieczna/bezpośrednia/szybka/efektywna) i brak narzędzi umożliwiających komfortowe funkcjonowanie osobom niewidomym.

Rozwiązanie: W ramach innowacji stworzono całkowicie wyciemniony oraz wygłuszony kask, który dzięki możliwości odsłuchiwania w nim nagrań binauralnych, imitujących czynności życia codziennego, przyspiesza rehabilitację oraz poprawia jakość życia osób, które niedawno utraciły lub w niedalekim czasie utracą wzrok. Dzięki specjalnej technice nagrywania dźwięku kask umożliwia słuchaczowi odsłuch i precyzyjną lokalizację w przestrzeni zarejestrowanych sygnałów akustycznych, a tym samym stwarza dźwiękową iluzję przebywania w miejscu, w którym dokonywano nagrania.

Dla kogo: Osoby z niepełnosprawnością narządu wzroku – zarówno te, które niedawno utraciły wzrok czy osoby niedowidzące, jak i osoby, które w niedługim czasie go utracą.

Kto może skorzystać: Osoby z niepełnosprawnością narządu wzroku, organizacje zajmujące się rehabilitacją osób niewidomych.

Czy to działa: Nagrania binauralne według uczestników badania są dobrą formą rewalidacji i rehabilitacji osób świeżo tracących wzrok lub takich które w niedalekiej przeszłości ten wzrok utraciły. Testerzy uważali, że wykorzystanie takiego rodzaju nagrań może pokazać osobom tracącym wzrok lub tym, które w ostatnim czasie wzrok utraciły jak wygląda życie z perspektywy osoby niewidomej. W trakcie testów, wiele razy poruszany był temat nagrań z tematyki sportu, które mogłyby zachęcić osoby z niepełnosprawnością do uprawiania sportu w formie rekreacyjnej, rehabilitacyjnej czy wyczynowej. Aspekt poruszania się samodzielnego czy to przy wykorzystaniu białej laski czy psa przewodnika był jednak najczęściej zgłaszaną formą nagrań używanej w tej formie terapii. Uczestnicy najczęściej zwracali uwagę że właśnie w tym aspekcie mają największy problem oraz największy lęk przed wyjściem z „bezpiecznego” domu. Sam kask był problemem ze względu na spory ciężar i zamknięty przedni panel, co w temperaturze bliskiej lub wyższej niż pokojowa stanowi duży dyskomfort przy użytkowaniu.

Autorzy: Tomasz Koźmiński

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'W ramach innowacji stworzono całkowicie wyciemniony oraz wygłuszony kask, który dzięki możliwości odsłuchiwania w nim nagrań binauralnych, imitujących czynności życia codziennego, przyspiesza rehabilitację oraz poprawia jakość życia osób, które niedawno utraciły lub w niedalekim czasie utracą wzrok. Dzięki specjalnej technice nagrywania dźwięku kask umożliwia słuchaczowi odsłuch i precyzyjną lokalizację w przestrzeni zarejestrowanych sygnałów akustycznych, a tym samym stwarza dźwiękową iluzję przebywania w miejscu, w którym dokonywano nagrania.',
        ARRAY['type:innovation', 'area:niepelnosprawnosc', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    ),
    (
        'kody-qr-na-pomoc-seniorom',
        'Kody QR na pomoc seniorom',
        'Problem: Innowacja odpowiada na trudności w samodzielnym poruszaniu się seniorów poza domem i problemów wynikających z zaburzeń pamięci, chorób przewlekłych bądź otępiennych.

Rozwiązanie: Innowacja dostarcza narzędzia w postaci unikalnych kodów QR dla seniorów, generowanych poprzez specjalnie do tego przygotowaną platformę internetową. Model składa się z fizycznie dostępnych naszywek lub naklejek z kodami, umieszczanych na ubraniu seniora, innych częściach garderoby, czy rzeczach osobistych. Kody QR mają stanowić narzędzie pomocy osobom starszym cierpiącym na zaniki pamięci, demencję, choroby otępienne. Po odczytaniu kodu przy pomocy telefonu, osoba gotowa do udzielenia pomocy może mieć dostęp do podstawowych informacji o seniorze.

Dla kogo: Osoby starsze, w tym osoby z zaburzeniami pamięci czy chorobami otępiennymi

Kto może skorzystać: Organizacje pozarządowe, służby ratownictwa medycznego, placówki podstawowej opieki zdrowotnej, jednostki organizacyjne pomocy społecznej, instytucje publiczne działające na rzecz seniorów, np. Centra Aktywności Seniorów.

Czy to działa: Choć użyteczność innowacji można ocenić wysoko, rozwiązanie wymaga udoskonalenia przede wszystkim w zakresie komunikacji i zapewnienia bezpieczeństwa oraz ponownego testowania (trudno chociażby w tym momencie ocenić trwałość materiałów z których są zrobione wszywki/naklejki). Rozwiązanie wymaga udoskonalenia m.in. pod względem zapewnienia bezpieczeństwa osobie posiadającej wklejony/naszyty kod oraz osobie skanującej kod, która byłaby gotowa udzielić pomocy. Należy także ponownie rozważyć zakres udostępniania danych oraz zdefiniować osoby, które mogłyby mieć do nich dostęp.

Autorzy: Fundacja Internationaler Bund Polska

Źródło: Biblioteka innowacji społecznych ROPS w Krakowie.',
        'Innowacja dostarcza narzędzia w postaci unikalnych kodów QR dla seniorów, generowanych poprzez specjalnie do tego przygotowaną platformę internetową. Model składa się z fizycznie dostępnych naszywek lub naklejek z kodami, umieszczanych na ubraniu seniora, innych częściach garderoby, czy rzeczach osobistych. Kody QR mają stanowić narzędzie pomocy osobom starszym cierpiącym na zaniki pamięci, demencję, choroby otępienne. Po odczytaniu kodu przy pomocy telefonu, osoba gotowa do udzielenia pomocy może mieć dostęp do podstawowych informacji o seniorze.',
        ARRAY['type:innovation', 'area:seniorzy', 'source:rops-biblioteka']::text[],
        '',
        NULL,
        'published'
    )
ON CONFLICT (id) DO NOTHING;

-- rows seeded earlier without a film get it; a film an admin set stays
UPDATE innovations SET page_url = 'https://www.youtube.com/watch?v=o7UhDlebLJo' WHERE id = 'bawita' AND page_url IS NULL;
UPDATE innovations SET page_url = 'https://www.youtube.com/watch?v=Bt6FF2Z5XU4' WHERE id = 'bez-presji-z-depresji' AND page_url IS NULL;
UPDATE innovations SET page_url = 'https://www.youtube.com/watch?v=QgkpdYndqNU' WHERE id = 'czas-na-aktywnosc' AND page_url IS NULL;
UPDATE innovations SET page_url = 'https://www.youtube.com/playlist?list=PLyL3RjFzJ8dH3ehTgdzxLYMF5YhNdnHEj' WHERE id = 'dialog-ponad-kulturami' AND page_url IS NULL;
UPDATE innovations SET page_url = 'https://www.youtube.com/watch?v=ev173g-d_vA' WHERE id = 'edki-kredki-terapeutyczne' AND page_url IS NULL;
UPDATE innovations SET page_url = 'https://www.youtube.com/watch?v=BoAC-J1Owr4' WHERE id = 'gluchy-czytelnik-w-bibliotece' AND page_url IS NULL;
UPDATE innovations SET page_url = 'https://www.youtube.com/watch?v=m5uEjEV0eDY' WHERE id = 'go-ahead-mow-smialo' AND page_url IS NULL;
UPDATE innovations SET page_url = 'https://www.youtube.com/watch?v=YRzg98fveHc' WHERE id = 'gra-o-zdrowie' AND page_url IS NULL;
UPDATE innovations SET page_url = 'https://www.youtube.com/watch?v=uDLOSoCb3E8' WHERE id = 'hear-it' AND page_url IS NULL;
UPDATE innovations SET page_url = 'https://www.youtube.com/watch?v=q31uQ435YAo' WHERE id = 'himalaje-autyzmu' AND page_url IS NULL;
UPDATE innovations SET page_url = 'https://www.youtube.com/watch?v=kE9lpr4OJPQ' WHERE id = 'hop-hop' AND page_url IS NULL;
UPDATE innovations SET page_url = 'https://www.youtube.com/watch?v=ScqdHaNxYa8' WHERE id = 'innotextil' AND page_url IS NULL;
