from dataclasses import dataclass

import httpx

from app.services.admin.errors import UpstreamUnavailableError

# a dead rag host should fail fast; only the response may take long
CONNECT_TIMEOUT_SECONDS = 5


@dataclass(frozen=True)
class RagAnswer:
    # rag's one-sentence summary of the query, generated by its llm
    answer: str
    # best first
    innovation_ids: list[str]


class RagClient:
    def __init__(self, base_url: str, timeout_seconds: float, query_timeout_seconds: float) -> None:
        self._base_url = base_url.rstrip("/")
        self._timeout = timeout_seconds
        self._query_timeout = query_timeout_seconds

    def embed_pdf(self, innovation_id: str, filename: str, pdf: bytes) -> None:
        # rag replaces all chunks of the innovation, so a retry is harmless
        res = httpx.post(
            f"{self._base_url}/embed/pdf",
            data={"innovation_id": innovation_id, "source": filename},
            files={"file": (filename, pdf, "application/pdf")},
            timeout=self._timeout,
        )
        res.raise_for_status()

    def query(self, text: str, top_k: int) -> RagAnswer:
        # no city filter: rag matches city exactly, which would hide innovations from other towns
        try:
            res = httpx.post(
                f"{self._base_url}/query",
                json={"query": text, "top_k": top_k},
                timeout=httpx.Timeout(self._query_timeout, connect=CONNECT_TIMEOUT_SECONDS),
            )
            res.raise_for_status()
            body = res.json()
            return RagAnswer(
                # rag dropped the llm answer; keep it optional so either version works
                answer=body.get("answer", ""),
                innovation_ids=[m["innovation_id"] for m in body["matches"]],
            )
        except (httpx.HTTPError, ValueError, KeyError) as exc:
            raise UpstreamUnavailableError(f"rag query failed: {exc}") from exc
